### ISSUE TITLE
Runtime .proto parsing

### ISSUE THREAD

**Issue by luke-jr** [protobuf-c/protobuf-c#164]
It'd be nice to be able to handle .proto files at runtime. I have code that dynamically converts any protobuf-c structure to JSON and vice-versa (via Jansson), but protobuf-c needs the code generation so it can't be a completely generic interface

**Comment by chrisdew** [comment]
+1 http://stackoverflow.com/questions/28433976/converting-protocol-buffers-to-from-json-in-c-without-generating-c-code

**Comment by FabioBatSilva** [comment]
+1 

I'd love to see this feature implemented,
If you guys need some help and are willing to point me to the right direction I can help..

**Comment by kondrenkov** [comment]
+1

**Comment by FeiWongReed** [comment]
+265

**Comment by lipnitsk** [comment]
Since the library already provides all that is needed - maybe except oneof names - I am closing this issue. This work is out of scope for protobuf-c
