### ISSUE TITLE
Is Visual Studio 2010 support needed?

### ISSUE THREAD

**Issue by alex85k** [protobuf-c/protobuf-c#170]
Currently protobuf-c gives some errors when compiled under VS2010. Is the support officially dropped (4 years passed...) or is it better to fix them?
The errors: https://gist.github.com/alex85k/3be875b74924e8643140
P.S. Protobuf 2.6 compiles...

**Comment by dkonigsberg** [comment]
I'm using protobuf-c on a project that has to build in VS2012, which has the same C89 limitations as VS2010.  As such, using the recent versions of this library required a number of build fixes.

**Comment by lipnitsk** [comment]
There have been a number of fixes to address cross-platform compilation issues. Please reopen with a detailed log from the latest protobuf-c release if this is still a problem.
