### ISSUE TITLE
Darndest segfault with Xcode 6 / clang 3.5

### ISSUE THREAD

**Issue by sodabrew** [protobuf-c/protobuf-c#171]
I am working on debugging this, want to get a report out in case I'm doing something obviously wrong.

`protoc-c` segfaults with or without valid arguments here:

``` shell
* thread #1: tid = 0x20aeaf, 0x00000001000c489a protoc-c`google::protobuf::compiler::CommandLineInterface::ParseArguments(this=0x00007fff5fbff7f8, argc=1, argv=0x00007fff00000000) + 42 at command_line_interface.cc:824, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x7fff00000000)
    frame #0: 0x00000001000c489a protoc-c`google::protobuf::compiler::CommandLineInterface::ParseArguments(this=0x00007fff5fbff7f8, argc=1, argv=0x00007fff00000000) + 42 at command_line_interface.cc:824
   821
   822 	CommandLineInterface::ParseArgumentStatus
   823 	CommandLineInterface::ParseArguments(int argc, const char* const argv[]) {
-> 824 	  executable_name_ = argv[0];
   825
   826 	  // Iterate through all arguments and parse them.
   827 	  for (int i = 1; i < argc; i++) {
```

And here:

``` shell
#3  0x000000010001b719 in google::protobuf::compiler::c::MakeKeywordsMap () at string:243
```

**Comment by lipnitsk** [comment]
@sodabrew, please provide more information or I would have to close the issue again due to the lack of data.

**Comment by lipnitsk** [comment]
@sodabrew From the dump in the top post, this looks like an issue in the Google protoc code. Does Google's protoc crash as well or does only protoc-c crash?

**Comment by sodabrew** [comment]
Google `protoc` did not crash, only when used via `protoc-c`. I recompiled `protoc` and then recompiled `protoc-c` and it does work now. I'll chalk this up to the usual C++ ABI weevils. Might have been an Xcode 6.1.1 fix in December. Or just PEBKAC :|
