### ISSUE TITLE
protobuf_c_message_free_unpacked segfaults on malformed messages

### ISSUE THREAD

**Issue by Sannis** [protobuf-c/protobuf-c#177]
Example code:
```c
  Foo__Bar *bar = calloc(1, foo__bar__descriptor.sizeof_message);
  foo__bar__init(bar);

  bar->n_bazes = 1;
  bar->bazes = NULL;

  foo__bar__free_unpacked(bar, NULL);
```

Example proto:
```proto
package Foo;

message Bar {
  repeated string bazes = 1;
}
```

Should it be fixed or not?

**Comment by Sannis** [comment]
Also `protobuf_c_message_free_unpacked(NULL, NULL)` caused segfault.

**Comment by lipnitsk** [comment]
@Sannis, I think that it would not hurt if the protobuf-c library was more resilient to invalid inputs, however your usage of `*_free_unpacked` is a bit of an edge-case here. `protobuf_c_message_free_unpacked` and its generated equivalents are meant to be called to free a message that was previously unpacked with `protobuf_c_message_unpack` (or its generated equivalent), and not just by itself. That way, the message would not be invalid when it is freed.

That said, I don't see how adding some NULL checks to `protobuf_c_message_free_unpacked` would hurt. Please add a test case or two to exercise this path and propose a code change that would fix the issue by opening a Pull Request.
