### ISSUE TITLE
Set the "project moved" flag on the Google Code project

### ISSUE THREAD

**Issue by lipnitsk** [protobuf-c/protobuf-c#186]
Google code will [cease to exist](http://google-opensource.blogspot.com/2015/03/farewell-to-google-code.html) on January 25, 2016.

The https://code.google.com/p/protobuf-c/ project already points to GitHub on its pages, but there is a cleaner way to [mark the project as moved](https://code.google.com/p/support-tools/wiki/GitHubExporterFAQ#Setting_the_%22Project_Moved%22_Flag):

>Setting the "Project Moved" Flag

>Once a project has been successfully exported to GitHub, you will want to update your project's homepage on Google Code to avoid confusion.

>Some project owners simply update their project homepage's text to indicate it has moved to GitHub. For example subtext or bwapi.

>Another option is to set the Google Code "project moved" flag. When set, attempts to access the project will take users to an interstitial page indicating the new project location. In the future, the page will automatically redirect to well-known project hosting services such as github.com.

>To set the "project moved" flag, navigate to your project's advanced admin page, at https://code.google.com/p/protobuf-c/adminAdvanced.

>Once there, enter the new project home page URL under "project moved". For example: https://github.com/protobuf-c/protobuf-c. Finally click the "Project Moved" button.

**Comment by edmonds** [comment]
Looks like I missed the window of opportunity for doing this. Oh well :-(
