### ISSUE TITLE
build fail with vc++ 2010

### ISSUE THREAD

**Issue by guodatou** [protobuf-c/protobuf-c#190]
when I move protobuf-c to vc++ project, but vc++ 2010 can't build it ?
here is an error

IntelliSense: expected an expression	src\protobuf-c\protobuf-c.c	177	2

static ProtobufCAllocator protobuf_c__allocator = {
	.alloc = &system_alloc,
	.free = &system_free,
	.allocator_data = NULL,
};

**Comment by edmonds** [comment]
Probably your compiler is too old and doesn't support designated initializers.
