### ISSUE TITLE
No message index number available

### ISSUE THREAD

**Issue by dilavni** [protobuf-c/protobuf-c#191]
The c++ version offers descriptor()->index() which is an integer that gives me the index number of any given message within the proto package. This information doesn't seem to be available in protobuf-c (am I mistaken?). I could perhaps try and take a look at adding this myself, but I'm not that familiar with traditional C. Would the changes be extensive or trivial?

**Comment by edmonds** [comment]
I don't believe `protobuf-c` has any package-level or file-level descriptors, so I'd imagine the changes would be somewhat extensive.
