### ISSUE TITLE
proto3

### ISSUE THREAD

**Issue by wattgo** [protobuf-c/protobuf-c#192]
Hi,
Is there any plan to support protobuf version 3 ?

**Comment by tylerhi** [comment]
+1

**Comment by bmiklautz** [comment]
Also having support for v3 would really be great.

**Comment by nacho** [comment]
protobuf just bumped the c# generator to support only proto3, this is pretty bad for us where our server uses protoc-c and the client c#. Is protoc-c going to support proto3 anytime soon? Thanks

**Comment by edmonds** [comment]
@nacho, can you point me to that change in the protobuf C# generator? Google has said "we will continue to support proto2 for a long time" in their release notes, so that's disappointing if true.

**Comment by pbor** [comment]
commit 493e3db98532e99a53cec914d8f4827a556ee408
Author: Jon Skeet <jonskeet@google.com>
Date:   Wed Jul 1 17:11:17 2015 +0100

    Codegen changes to support descriptor runtime changes
    
    - Add a partial method called by all constructors
    - Generate internal classes for descriptor.proto (only)
    - Forbid proto2 descriptors except for descriptor.proto


And the README now says:

This code is still under significant churn. Unlike the original port,
it only supports proto3 (but not *all* of proto3 yet) - there are no
unknown fields or extensions, for example. protoc will (eventually)
deliberately fail if it is asked to generate C# code for proto2
messages other than descriptor.proto, which is still required for
reflection. (It's currently exposed publicly, but won't be
eventually.)

**Comment by pbor** [comment]
I started to investigate this, here is what we discovered 

The good news is:

1. Compiling protobuf-c against protobuf 3 works out of the box
2. Once you do that, protibuf-c is able to process proto3 files without any problems and create .c and .h files
3. As far as I understand the syntax changes have very little impact on the serialization so at this point using protobuf-c on one side and C# on the other just works.

So what needs to be fixed? The only thing I found is that in proto3 all fields are optional by default and there are no required fields. This means that today every foo field has a corresponding has_foo in the struct, that needs to be set manually, which is pretty inconvenient. The second thing is that we should avoid to serialize fields which have the builtin default value (0, NULL, etc), sending such value is not a problem, but it is extra work we could avoid (or maybe not? my guess here is that we memset to 0 and then explicitely set again the field to 0, but maybe that is already avoided). 


it would be great to have some feedback on which way you think it is best to proceed. In particular

1. for the generator it is relatively easy: the FileDescriptor has now a syntax() method that we can use to decide whether to emit has_foo or not. However this descriptor today is not propagated does to each class that generates the code. I can see two approaches: propagate this to each class and then in each point where we emit "has_foo" add an "if" or emit a "#define PROTOBUF_C__SYNTAX 3" at the start of the .h file and then emit unconditionally "#ifdef SYNTAX < 3 \n boolean has_field \n #endif"

2. For the runtime library it is trickier... how do store this info? one possibility is to use one of the reserved fields in the ProtobufCMessageDescriptor struct to point to a ProtobufCFileDescriptor struct which in turns contains the syntax version. At this point when serializing we could consult field_descriptor->message_descriptor->file_descriptor->syntax and decide whethere we should use the "has_foo" field or if instead we should check "foo != 0". However I am worried that all this dereferencing for each single field is not very efficient...

**Comment by pbor** [comment]
https://github.com/protobuf-c/protobuf-c/pull/228

**Comment by andygikling** [comment]
I'm testing this pull request.  I'll let you know what I find.

**Comment by andygikling** [comment]
I've been testing #228 and it's working quite well.  I'm generating version 3 Protobuf messages from C# and sending them to a Microchip PIC32MZ and everything is working great.  Messages generated by the PIC32MZ are also being deserialized correctly in C#.  I'm very pleased.

So far I've exercised the following features:  Enums, Nested Messages, Optional Fields, Bools, Int32s, Doubles, Strings.  

I'm in the process of testing Repeated and Required Fields.  More to come.

**Comment by inelukik** [comment]
Any idea when the support for proto3 will be ready? Or a beta version is also oke for me.

**Comment by pbor** [comment]
The patch in the PR is working as far as I know

**Comment by tylerjwatson** [comment]
Is this still being maintained? v3 is mainline in the upstream protobuf now.

**Comment by andygikling** [comment]
Tyler,

I tested it a while ago and it worked well.  We are having a hard time getting the maintainer to pull these changes in to the project...

Nobody can seem to get a hold of them.

Hey guys!  Pull this patch in!  Fix the tests, and let's embrace protobuf 3 a bit!

**Comment by pbor** [comment]
The project is maintained. It is not moving fast because it is working and reliable. I guess the maintainers use it for a proto2 codebase and that is where their main interest is. However Robert replied to the pull request last week, and I have updated my PR accordingly.

I am surely eager to get proto3 support in, but we should be thanking Robert and Ilya, not complaining.

The best way to help is to actually try my branch and report back if it works as expected (as Andy did, thanks!)

**Comment by andygikling** [comment]
Ok thanks Paolo.  Good to hear they got back to you!

**Comment by doodles526** [comment]
Can this be closed now that #228 was merged a few days back?

**Comment by doodles526** [comment]
Sorry. Just realized it was merged to `next` and not yet to `master`

**Comment by bryanteague** [comment]
I think I found a bug using the current code with proto3. I'm using a protobuf with two layers of nested repeated submessages, in other words I have a subsubmessage. I can populate the fields just fine, but packing the buffer turns all the subsubmessage values to 0. The other fields in the submessage are sent fine. Switch to proto2 fixes the issue.

**Comment by edmonds** [comment]
@bryanteague Can you please report this as a new issue?

**Comment by bryanteague** [comment]
Added as new issue: #262

**Comment by mbencik** [comment]
Is in protobuf-c proto 3 suported by now? I would like to test the performance of protobuf-c compared to protobuf.

**Comment by pbor** [comment]
Yes.

Il Dom 22 Lug 2018, 16:40 mbencik <notifications@github.com> ha scritto:
