### ISSUE TITLE
Wiki link to examples is broken

### ISSUE THREAD

**Issue by hultqvist** [protobuf-c/protobuf-c#194]
This page

https://github.com/protobuf-c/protobuf-c/wiki/Examples

Has this broken link

Examples of using [protobuf-c](http://www.google.com/codesearch/p?hl=en#Cn85FSbHSs0/trunk/Dependencies/protobuf-2.0.3/src/protobuf-c.c&q=protobuf-c&d=4).

http://www.google.com/codesearch/p?hl=en#Cn85FSbHSs0/trunk/Dependencies/protobuf-2.0.3/src/protobuf-c.c&q=protobuf-c&d=4

**Comment by lipnitsk** [comment]
Fixed to point to https://github.com/protobuf-c/protobuf-c
