### ISSUE TITLE
Enums with negative values do not get processed correctly

### ISSUE THREAD

**Issue by lipnitsk** [protobuf-c/protobuf-c#199]
Packing an enum value of any negative value should yield a 10-byte two's complement of a 64-bit integer, since enums use a base-128 varint encoding.

From the [Google Protobuf Language Guide](https://developers.google.com/protocol-buffers/docs/proto#enum):
> Enumerator constants must be in the range of a 32-bit integer. Since enum values use varint encoding on the wire, negative values are inefficient and thus not recommended.

With the current version of protobuf-c, the result of encoding an enum value of `-1` is `08 ff ff ff ff 0f`, whereas it should be `08 ff ff ff ff ff ff ff ff ff 01`. Essentially the bug is that enums today are encoded as `uint32` numbers, but they need to be encoded as `int32`'s instead.

**Comment by lipnitsk** [comment]
@edmonds, I'm about to push a fix for this. It might be a good idea to make a special release with this fix.

**Comment by lipnitsk** [comment]
@edmonds are you planning to make a release anytime soon?

**Comment by edmonds** [comment]
I'd be happy to release `next` as 1.2.0 sometime next week!
