### ISSUE TITLE
How does "_get_packed_size" work when a message member is "repeated"

### ISSUE THREAD

**Issue by sphoorthi-dayanand** [protobuf-c/protobuf-c#208]
Hi All,

I have just started using Google Protocol Buffers and I am a little confused with the "get_packed_size" function.
For example, in the address book example, we see the following:

message AddressBook {
  repeated Person person = 1;
}

After compiling to generate C code, following function is defined:

size_t tutorial__address_book__get_packed_size
                     (const Tutorial__AddressBook *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &tutorial__address_book__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}

Since we dont know what will be the number of occurrences of the message "Person" within "AddressBook", how will the output of above function be generated?

Thanks and Regards,
Sphoorthi Dayanand

**Comment by edmonds** [comment]
The discussion group is here: https://groups.google.com/forum/#!forum/protobuf-c.
