### ISSUE TITLE
Add static maximum message size

### ISSUE THREAD

**Issue by bestouff** [protobuf-c/protobuf-c#210]
Hi,

It would be handy if one could add a static #define describing the maximum size a packed buffer can grow, for embedded systems development where dynamic allocations should be kept at a minimum.
Of course this wouldn't work for e.g. repeated fields, except if an option specifying their max size was introduced.

That would replace the MAX_MSG_SIZE in the "Simple complete example" in https://github.com/protobuf-c/protobuf-c/wiki/Examples

**Comment by edmonds** [comment]
I think this use case should already be possible with `protobuf_c_message_pack_to_buffer()`. Pass a custom callback function via the `ProtobufCBuffer` argument that enforces a maximum size.
