### ISSUE TITLE
Tests do not build with cmake/visual studio

### ISSUE THREAD

**Issue by nacho** [protobuf-c/protobuf-c#227]
First error that I have with a new protobuf is the next:

<verbatim>
diff --git a/t/test-full.proto b/t/test-full.proto
index c04fce7..1d73106 100644
--- a/t/test-full.proto
+++ b/t/test-full.proto
@@ -1,3 +1,5 @@
+syntax = "proto2";
+
 package foo;

 message SubMess {
diff --git a/t/test-optimized.proto b/t/test-optimized.proto
index d126881..1a090e5 100644
--- a/t/test-optimized.proto
+++ b/t/test-optimized.proto
@@ -1,3 +1,5 @@
+syntax = "proto2";
+
 package foo;

 option optimize_for = CODE_SIZE;
diff --git a/t/test.proto b/t/test.proto
index bc94f13..90f9e9d 100644
--- a/t/test.proto
+++ b/t/test.proto
@@ -1,3 +1,5 @@
+syntax = "proto2";
+
 package foo;

 message Person {
</verbatim>

I had to add this patch to fix a compile error. But then I get also this one:
C:\gtk-build\build\Win32\debug\protobuf-c\t\generated-code2\test-generated-code2
.c(5) : fatal error C1083: Cannot open include file: 't/test-optimized.pb-c.h':
No such file or directory
NMAKE : fatal error U1077: 'C:\PROGRA~2\MICROS~1.0\VC\bin\cl.exe' : return code

**Comment by alex85k** [comment]
As I see, this is mostly fixed in 'next' branch, master branch with minimal cmake fix is here:
https://github.com/alex85k/protobuf-c/commits/master
