### ISSUE TITLE
Bad enums with multiple oneofs

### ISSUE THREAD

**Issue by jwearing** [protobuf-c/protobuf-c#251]
Hello,

I think I have found a bug in the enum generation for oneof fields.  It seems to only occur when there are multiple oneofs in the same message.  Here is a simple example:

```
message two_oneofs {
  oneof first_oneof {
    bool a = 10;
    bool b = 11;
  }

  oneof second_oneof {
    bool c = 20;
    bool d = 21;
  }
}
```

Compiles into:

```
typedef enum {
  TWO_ONEOFS__FIRST_ONEOF__NOT_SET = 0,
  TWO_ONEOFS__FIRST_ONEOF_A = 10,
  TWO_ONEOFS__FIRST_ONEOF_B = 11
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(TWO_ONEOFS)
} TwoOneofs__FirstOneofCase;

typedef enum {
  TWO_ONEOFS__SECOND_ONEOF__NOT_SET = 0,
  TWO_ONEOFS__SECOND_ONEOF_C = 20
  TWO_ONEOFS__SECOND_ONEOF_D = 21
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(TWO_ONEOFS)
} TwoOneofs__SecondOneofCase;
```

Note the lack of a comma after "20" in the second enum.  When compiling, gcc gives this error:

```
In file included from two_oneofs.pb-c.c:9:0:
two_oneofs.pb-c.h:36:3: error: expected ‘,’ or ‘}’ before ‘TWO_ONEOFS__SECOND_ONEOF_D’
   TWO_ONEOFS__SECOND_ONEOF_D = 21
   ^
```

Also, the name of the last item is the same in both enums.  
```
In file included from two_oneofs.pb-c.h:7:0,
                 from two_oneofs.pb-c.c:9:
two_oneofs.pb-c.h:37:5: error: redeclaration of enumerator ‘_TWO_ONEOFS_IS_INT_SIZE’
     PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(TWO_ONEOFS)
     ^
two_oneofs.pb-c.h:30:5: note: previous definition of ‘_TWO_ONEOFS_IS_INT_SIZE’ was here
     PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(TWO_ONEOFS)
     ^
```

It seems to work correctly on master.  The problem occurred for me while working with the pbor/wip/proto3 branch.  @pbor commented "that problem is present on the "next" branch, so it is not related to my patch. I think it was introduced in PR 220. Please file a sepaarate issue about it".

Thanks

**Comment by edmonds** [comment]
Hi, jwearing:

This should be fixed on `next` now. Thanks for the report!
