### ISSUE TITLE
proto3 and nested submessages

### ISSUE THREAD

**Issue by bryanteague** [protobuf-c/protobuf-c#262]
I think I found a bug using the current code with proto3 syntax. I'm using a protobuf with two layers of nested repeated submessages, in other words I have a subsubmessage. I can populate the fields just fine, but packing the buffer turns all the subsubmessage values to 0. The other fields in the submessage are sent fine. Switching back to proto2 fixes the issue.

**Comment by edmonds** [comment]
@pbor Can you take a look at this?

**Comment by pbor** [comment]
I will try to have a look in the weekend.

@bryanteague can you attach a test proto file?

**Comment by bryanteague** [comment]
If you can't recreate the issue with the following let me know and we'll dig deeper. 

`syntax = "proto3";

message myMessage{
	repeated mySubMessage a  			= 1;

	message mySubMessage{
		uint32 a 						= 1;
		double b 						= 2;
		
		repeated mySubSubMessage c 	= 3 [packed=true];

		message mySubSubMessage{
			int32 a 					= 1;
			int32 b 					= 2;
		}
	}
}`

**Comment by bryanteague** [comment]
See the following. If you can't recreate the issue with this, we'll dig a little deeper.

```protobuf
syntax = "proto3";

message myMessage{
    repeated mySubMessage a             = 1;

    message mySubMessage{
        uint32 a                        = 1;
        double b                        = 2;
        
        repeated mySubSubMessage c      = 3;

        message mySubSubMessage{
            int32 a                     = 1;
            int32 b                     = 2;
        }
    }
}
```

**Comment by pbor** [comment]
I cannot reproduce.

I pushed a unit test here: https://github.com/pbor/protobuf-c/commit/57309f92edf2079fe09767a7c4d5321984590e19

If possible try to change it so that it exposes the problem

**Comment by pbor** [comment]
Actually upon closer inspection even if the test passes valgrind shows a problem.

I opened CR #264 to fix the problem detected by valgrind and hopefully it also fixes what you are seeing

**Comment by edmonds** [comment]
@bryanteague Can you try again with the current `next` branch?

**Comment by pbor** [comment]
@edmonds I have been thinking about it some more and I think my last patch is not correct :(

The patch avoids the valgrind error but it does not detect unset scalar values as beeing "zeroish". This is not too bad it just means we will send 0 instead of being implicit, but I would like to understand what it going on...

The code I added is

`
static protobuf_c_boolean
field_is_zeroish(const ProtobufCFieldDescriptor *field,
		 const void *member)
{
	if (field->type == PROTOBUF_C_TYPE_MESSAGE ||
	    field->type == PROTOBUF_C_TYPE_STRING)
	{
	    const void *ptr = *(const void * const *) member;
	    if (ptr == NULL) {
		printf("%s NULL POINTER\n", field->name);

		    return TRUE;
		}
	}

	return member == NULL;
}
`

however member is message + offset so it cannot ever be null, so the check at the end is useless. Beside if the problem was a null pointer we would have crashed, not seen a valgrind error about uninitialized memory.

Logically I think that want to do is check if (*memeber) == 0 for any field (like the old code did).

The problem is that if I do
`
const void *ptr = *(const void * const *) member;
`
for fields that are not strings or submessages, valgrind says we are accessing uninitialized memory.

However the generated _INIT macro initializes all fields to 0.

What am I missing?

**Comment by pbor** [comment]
Ok, I reworked is_zeroish one more time, PR #267 

Please check if my reasoning is correct or if you see a simpler way

Sorry for the multiple attempts :(

**Comment by pbor** [comment]
@bryanteague did you manage to test?

**Comment by bryanteague** [comment]
Is there a missing header file (issue262.pb-c.h)?

**Comment by bryanteague** [comment]
Nevermind, not paying attention. Will get back to you later today.

**Comment by bryanteague** [comment]
So I am in fact getting an error with your test function, but not exactly
the one I reported.

Assertion `msg2->a[0]->b == 6' failed

The value here is actually 0. So here I am getting an error in a
submessages, not a subsubmessages. The rest of the assertions pass so the
subsubmessages are packed and unpacked okay.

Again if I switch the syntax of the .proto file to proto2 and add
"required" the test passes.

Let me know what else I can provide.

-Bryan

**Comment by pbor** [comment]
I have not updated that branch. I meant : can you test your code with the
current 'next' branch?

Il 14/Apr/2017 20:58, "bryanteague" <notifications@github.com> ha scritto:

> So I am in fact getting an error with your test function, but not exactly
> the one I reported.
>
> Assertion `msg2->a[0]->b == 6' failed
>
> The value here is actually 0. So here I am getting an error in a
> submessages, not a subsubmessages. The rest of the assertions pass so the
> subsubmessages are packed and unpacked okay.
>
> Again if I switch the syntax of the .proto file to proto2 and add
> "required" the test passes.
>
> Let me know what else I can provide.
>
> -Bryan
>

**Comment by bryanteague** [comment]
I did a quick test this morning and it seems like it fixed my problem.

Thanks!
