### ISSUE TITLE
Build broken using /google/protobuf master

### ISSUE THREAD

**Issue by michaelxusc** [protobuf-c/protobuf-c#268]
Building protobuf-c from source is broken as of [this commit](https://github.com/google/protobuf/commit/cbd08cb7d11fabbdf471d49ed13e5082033bd2b5#diff-cbd31ea2a5761cd281396b4277c36887)

The above commit removed "using namespace std" from stubs/common.h, which is included by proto-c/c_helpers.cc.

Specifically, adding std:: in this [line](https://github.com/protobuf-c/protobuf-c/blame/master/protoc-c/c_helpers.cc#L507) fixes the issue.

**Comment by djdeath** [comment]
Proposed fix in https://github.com/protobuf-c/protobuf-c/pull/270

**Comment by edmonds** [comment]
Should be fixed by #280.
