### ISSUE TITLE
make error on Ubuntu 14.0LTS

### ISSUE THREAD

**Issue by saumilagg** [protobuf-c/protobuf-c#278]
I cloned protobuf-c from git master and trying to make it run but i Have following errors:
![image](https://user-images.githubusercontent.com/8662112/28138859-39a8ba0c-6720-11e7-9c5a-eaffaf724ce8.png)

After configuring the output looks like this :

![image](https://user-images.githubusercontent.com/8662112/28138885-50648d20-6720-11e7-9032-87e737633a32.png)

I am wondering whats wrong there.

**Comment by NoMore201** [comment]
Same for me. Adding to the source files the following line
```
using namespace std;
```
solves the problem. I don't know what is causing this, I've always compiled protobuf-c successfully with any distro, but now on KDE Neon (Ubuntu 16.04 LTS) is giving error.

**Comment by RogerYaozhenyu** [comment]
@NoMore201  i faced the same error, but i follwd your steps. it' s still not work .the error messages is same as before.

**Comment by NoMore201** [comment]
@RogerYaozhenyu did you add the line in every header file (right after the include declarations) in the `protoc-c` subfolder?
I forgot to specify which file to edit.

**Comment by RogerYaozhenyu** [comment]
i added to some files, but not all. it's the same.....

**Comment by saumilagg** [comment]
I edited the header files as suggested by @NoMore201 But now it pulls up errors on t/test-full.pb.cc files. Like token errors.
 something like this:

/test-full.pb.cc: In member function ‘virtual bool foo::TestMess::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*)’:
t/test-full.pb.cc:5776:32: error: expected ‘<’ before ‘<:’ token
                 14, static_cast<::google::protobuf::uint64>(value));
                                ^
t/test-full.pb.cc:5776:32: error: expected type-specifier before ‘<:’ token
t/test-full.pb.cc:5776:32: error: expected ‘>’ before ‘<:’ token
t/test-full.pb.cc:5776:32: error: expected ‘(’ before ‘<:’ token
t/test-full.pb.cc:5776:34: error: expected identifier before ‘:’ token
                 14, static_cast<::google::protobuf::uint64>(value));

**Comment by saumilagg** [comment]
FIx for this : t/test-full.pb.cc and change all "static_cast<::google" to "static_cast< ::google". There needs to be a space after the "<". 

Its also in https://github.com/protobuf-c/protobuf-c/issues/275

You have to edit that file and builds fine now

**Comment by RogerYaozhenyu** [comment]
@saumilagg  could you list the header files which you edited? thanks very much.

**Comment by RogerYaozhenyu** [comment]
@saumilagg  thanks , i modified all header files . add using namespace to all header file in protoc-c directory.   it could work now.

**Comment by sangli00** [comment]
@saumilagg  hi This problem is fix now?  how to fix this error?

**Comment by edmonds** [comment]
Should be fixed in #280.
