### ISSUE TITLE
SYNTAX_PROTO3 check in file generator breaks on protobuf-2.x

### ISSUE THREAD

**Issue by JackPaul** [protobuf-c/protobuf-c#284]
protoc-c/c_file.cc: In member function ‘void google::protobuf::compiler::c::FileGenerator::GenerateHeader(google::protobuf::io::Printer*)’:
protoc-c/c_file.cc:123:14: error: ‘const class google::protobuf::FileDescriptor’ has no member named ‘syntax’
   if (file_->syntax() == FileDescriptor::SYNTAX_PROTO3) {
              ^
protoc-c/c_file.cc:123:26: error: ‘SYNTAX_PROTO3’ is not a member of ‘google::protobuf::FileDescriptor’
   if (file_->syntax() == FileDescriptor::SYNTAX_PROTO3) {
                          ^
make: *** [protoc-c/protoc_c_protoc_gen_c-c_file.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by EvanKrall** [comment]
Seems like the change in 712154b912de824741381c0bb26c2fbed54515a3 made protobuf-c require protobuf version 3+
