### ISSUE TITLE
Duplicated "base" field in the generated struct

### ISSUE THREAD

**Issue by hsllany** [protobuf-c/protobuf-c#287]
If I have a proto file like this:
```
syntax = "proto2";

package com.example;

message Student{
        required int32 base = 4;
        required string name = 1;
        required int32 age = 2;
        optional string email = 3;
}
```
It will generate the following struct in the header file:

```c
struct  _Com__Example__Student
{
  ProtobufCMessage base;
  int32_t base;
  char *name;
  int32_t age;
  char *email;
};
```

There are 2 "base" fields in this struct, which is illegal.

**Comment by wzy2687** [comment]
me too.

**Comment by dota17** [comment]
It seems that the variable name base is a "system reserved word" of protobuf-c. I think we shouldn't use these "system reserved words" in .proto files. Maybe there should be a document explaining this?

**Comment by lipnitsk** [comment]
Would renaming to `_base` address the problem? @edmonds can we rename `base` to `_base` without breaking code? Doesn't seem like it to me, so this might have to wait until 2.0.

**Comment by edmonds** [comment]
Renaming to `_base` would just make the problem less likely to occur. You could of course put a field named `_base` in the .proto file and run into the exact same problem. We would probably want to give the `ProtobufCMessage` field an ugly and unique name like `protobuf_c_message__base` or something.

I don't believe changing the name of this field would change the ABI, but I can't remember if there is a good use case for protobuf-c client code to manipulate the `base` field directly. If there isn't a lot of code out there directly referencing the `base` field it may be feasible to make the change in 1.x and bump `min_header_version` and/or `PROTOBUF_C_MIN_COMPILER_VERSION`.

What we don't want to do is make a change in protobuf-c 1.x that causes a bunch of protobuf-c using projects to have to update their code, like we did with the 0.x to 1.x transition. (Also, hopefully that transition made people stop committing .pb-c.{c,h} files to their source trees and generate them at runtime.)
