### ISSUE TITLE
Code generator binary

### ISSUE THREAD

**Issue by royben** [protobuf-c/protobuf-c#291]
Hey there, I am having difficulties compiling the projects on windows using Visual Studio 2017.
Is it possible to get my hands on the code generator exe required for producing the .c and .h files using .proto files?

Thanks!

**Comment by lipnitsk** [comment]
Sorry, there are no plans to publish binaries for any given platform. Maybe somebody has done so elsewhere. If you have a specific build issue, feel free to raise a ticket specific to that.
