### ISSUE TITLE
when I set member variables to default value, coding length will be 0 ？

### ISSUE THREAD

**Issue by shengweilin** [protobuf-c/protobuf-c#292]
uint8_t *buf1;
uint8_t len;

UserMessage__User linsw ;
user_message__user__init(&linsw);
linsw.name = ""  ;
linsw.age  = 0;
linsw.gender = 0;
linsw.id = 0;

len = user_message__user__get_packed_size( &linsw);  //  len ==0 ??

**Comment by shengweilin** [comment]
Checking if a field with a default value has been set  ?
I'm trying to figure out if an optional field has been set in a proto. Can you please explain how to check if a field has been set. Currently, I'm observing that if a field has a default value and is not set, then on decoding, the object contains the default value. How can we distinguish this from the case where the field was indeed set with the same value as the default?

**Comment by FSMaxB** [comment]
If these are optional fields, you have to set the `has_` boolean flags to `true` (`has_age`, `has_gender`, `has_id`).

The string has the length 0, so it won't show up either I guess.

**Comment by FSMaxB** [comment]
To check if it is set, after decoding, you just look at the `has_` flags again, to check if it is `true`.

**Comment by shengweilin** [comment]
I use proto3 ,  when I modify the  .proto file  " syntax = "proto2"; " and add optional fields .just  like this:

syntax = "proto2";
package user_message;

message user {
    optional string name = 1;
    optional int32 age = 2;
    optional bool grender = 3;
    optional int32  id = 4;     
}

then I do just like @FSMaxB said, the problem is solved ;
