### ISSUE TITLE
Compilation failure on Mac 10.12.5

### ISSUE THREAD

**Issue by nikitanerkar** [protobuf-c/protobuf-c#294]
In file included from protoc-c/c_bytes_field.cc:63:
./protoc-c/c_bytes_field.h:89:3: error: no template named 'map'; did you mean 'std::map'?
  map<string, string> variables_;
  ^~~
  std::map
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__tree:1454:78: note: 'std::map' declared here
    template <class, class, class, class> friend class _LIBCPP_TYPE_VIS_ONLY map;
                                                                             ^
protoc-c/c_bytes_field.cc:77:25: error: no template named 'map'; did you mean 'Map'?
                        map<string, string>* variables) {
                        ^~~
                        Map
/usr/local/Cellar/protobuf/3.4.1/include/google/protobuf/map.h:122:7: note: 'Map' declared here
class Map {
      ^
protoc-c/c_bytes_field.cc:89:3: error: no matching function for call to 'SetBytesVariables'
  SetBytesVariables(descriptor, &variables_);
  ^~~~~~~~~~~~~~~~~
protoc-c/c_bytes_field.cc:76:6: note: candidate function not viable: no known conversion from 'map<string, string> *' (aka 'map<basic_string<char, char_traits<char>, allocator<char> >,
      basic_string<char, char_traits<char>, allocator<char> > > *') to 'Map<string, string> *' (aka 'Map<basic_string<char, char_traits<char>, allocator<char> >, basic_string<char, char_traits<char>,
      allocator<char> > > *') for 2nd argument
void SetBytesVariables(const FieldDescriptor* descriptor,
     ^
3 errors generated.
make: *** [protoc-c/protoc_c_protoc_c-c_bytes_field.o] Error 1

**Comment by Julian** [comment]
Pretty sure this error means you're finding an incompatible version of `libproto` itself. (For me, changing from 3.5 to 3.3 made this go away).
