### ISSUE TITLE
Compile Error on Centos 7.3

### ISSUE THREAD

**Issue by nicktand** [protobuf-c/protobuf-c#305]
Hi,

I am on Centos 7.3 and trying to build protobuf-c. The configure part completes but when I did make I see an error 
Error
====
In file included from protoc-c/c_file.cc:64:0:
./protoc-c/c_file.h:107:3: error: ‘vector’ does not name a type
   vector<string> package_parts_;
   ^
protoc-c/c_file.cc: In constructor ‘google::protobuf::compiler::c::FileGenerator::FileGenerator(const google::protobuf::FileDescriptor*, const string&)’:
protoc-c/c_file.cc:114:44: error: ‘package_parts_’ was not declared in this scope
   SplitStringUsing(file_->package(), ".", &package_parts_);
                                            ^
make: *** [protoc-c/protoc_c_protoc_gen_c-c_file.o] Error 1

OS Details 
========
uname -a
Linux localhost.localdomain 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[centos@localhost protobuf-c]$ cat /etc/re
redhat-lsb/       request-key.conf  resolv.conf       
redhat-release    request-key.d/    
[centos@localhost protobuf-c]$ cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core) 

Configure Logs
============
protobuf-c 1.3.0

        CC:                     gcc -std=gnu99
        CFLAGS:                 -g -O2
        CXX:                    g++
        CXXFLAGS:               -g -O2
        LDFLAGS:                
        LIBS:                   

        prefix:                 /usr/local
        sysconfdir:             ${prefix}/etc
        libdir:                 ${exec_prefix}/lib
        includedir:             ${prefix}/include
        pkgconfigdir:           ${libdir}/pkgconfig

        bigendian:              no
        protobuf version:       libprotoc 2.5.0

Thanks

**Comment by hasanm** [comment]
I am having exactlyl the same error, in Debian wheezy.

**Comment by gathar** [comment]
Same Issue with SLES 12 SP3 and libprotoc 3.5.1.

**Comment by ilqp** [comment]
Exactly same issue.

Details are as following:

**Operating system:** Ubuntu 16.04.3 LTS (Linux **** 4.4.0-87 #110-ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

`CC:                gcc
CFLAGS:            -g -O2 
CXX:               g++
CXXFLAGS:          -g -O2
LDFLAGS:                    
LIBS:             

prefix:                 /usr/local
sysconfdir:         ${prefix}/etc
libdir:             ${exec_prefix}/lib
includedir:         ${prefix}/include
pkgconfigdir:       ${libdir}/pkgconfig

bigendian:          no
protobuf version:   libprotoc 3.5.1`

**Comment by adecroix** [comment]
I have also the same issue with my Ubuntu distribution...

**Comment by jupiterbt71** [comment]
You can  fix by change " vector package_parts_; "   to   "  std::vector package_parts_;" .

**Comment by adecroix** [comment]
Thanks for your help jupiterbt71.

So I had to replace vector by std::vector in all files.
After that, I had an error about "pair", so I replaced all the pair name by std::pair.

Seems to work now... Google should update the files no ?

**Comment by bman7903** [comment]
this is also known as declaring a scope if I am not mistaken, the implication being that vector can or is called from multiple areas of the program from different libraries sharing sed name.  Older versions of gcc allow this as implicit taking the first match or last call and rolling with it.  7.2 +... not so much.  If you read the error it explains itself.  Its the simplest error in any programming some times called not declaring a variable, or variable in scope  in C.  just sounds fancy in ++. in this case the std library is probably being called from C, C++, and static tr1(c++), not vector as you might guess. find the three locations and read the classes if you want to actually understand what is happening here and not just how to fix this one instance. then put sql unicode imports on the chopping block

**Comment by bman7903** [comment]
'-std=gnu++98' or CXX=clang++ should also work.  We roll with code from 1980 in our OS.  The only way its getting updated is if you yourself do it, and no one else will care.  your os would be much larger, and much slower.

**Comment by tassi-yuzukko** [comment]
thanks for the info! @jupiterbt71 @adecroix
