### ISSUE TITLE
Use protobuf-c without proto file?

### ISSUE THREAD

**Issue by erthalion** [protobuf-c/protobuf-c#307]
Hi,

First of all, thank you for this project!

I have a question, is it possible to use `libprotobuf-c` somehow to generate a protobuf messages without .proto file? For example, I have some data in json format, and I want to send it to a client (who has all the correct proto definitions for this data) in the protobuf format. Looks like it's more or less straightforward to generate .proto file from json, but can it be done without this intermediate step?

**Comment by isaachier** [comment]
@erthalion this is not specific to protobuf-c, but the original protocol buffers project by Google. Nevertheless, the answer essentially is no.
