### ISSUE TITLE
Running ./configure --prefix=/usr shows error message

### ISSUE THREAD

**Issue by sympthom** [protobuf-c/protobuf-c#317]
Hi, 

Running the command ./configure --prefix=/usr shows error message below:

checking google/protobuf/compiler/command_line_interface.h usability... no
checking google/protobuf/compiler/command_line_interface.h presence... no
checking for google/protobuf/compiler/command_line_interface.h... no
configure: error: required protobuf header file not found

What should I do about this?

Thanks,

Cheers,
Martin

**Comment by sympthom** [comment]
Protobuf is installed.

**Comment by KingElimy** [comment]
hey,have you resolved this? 
I am having exactly the same error.
Configure message as follow:
[root@localhost protobuf-c-1.3.0]# ./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... none needed
checking for gcc option to accept ISO Standard C... (cached) none needed
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking whether ln -s works... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking whether make supports nested variables... (cached) yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for doxygen... doxygen
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
**checking for protobuf... yes
checking google/protobuf/compiler/command_line_interface.h usability... no
checking google/protobuf/compiler/command_line_interface.h presence... no
checking for google/protobuf/compiler/command_line_interface.h... no
configure: error: required protobuf header file not found**

OS info:
[root@localhost protobuf-c-1.3.0]# uname -a
**Linux localhost.localdomain 3.10.0-862.2.3.el7.x86_64 #1 SMP Wed May 9 18:05:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux**

**Comment by markarsanious** [comment]
I have exactly the same problem! Did you guys reach a solution for this?

**Comment by KingElimy** [comment]
I just changed that pre-check，then ./configure succeed，but i cannot make sure it finally will work.
first,open your file,named configure.ac with an editor,go to line 85,where it is showed as
`  save_CPPFLAGS="$CPPFLAGS"
  CPPFLAGS="$save_CPPFLAGS $protobuf_CFLAGS"
  AC_CHECK_HEADERS([google/protobuf/compiler/command_line_interface.h],
                   [],
                   [AC_MSG_ERROR([required protobuf header file not found])])
  CPPFLAGS="$save_CPPFLAGS"`
just comment it all simply by add symbol '#' before every line,then it looks like this
`  save_CPPFLAGS="$CPPFLAGS"
  CPPFLAGS="$save_CPPFLAGS $protobuf_CFLAGS"
\#  AC_CHECK_HEADERS([google/protobuf/compiler/command_line_interface.h],
\#   [],
\#   [AC_MSG_ERROR([required protobuf header file not found])])
  CPPFLAGS="$save_CPPFLAGS"`
and then,run command 
`./autogen.sh`
which will generate new configure file, 
and last,run command
`./configure`
this time it should not occur the same error.
of course,you should make sure that header file google/protobuf/compiler/command_line_interface.h do exist somewhere.
good luck :-)

**Comment by dkopelove** [comment]
You need the protoc development headers. On ubuntu this package has the name libprotoc-dev.

**Comment by KingElimy** [comment]
@dkopelove  thanks for your reply, and i managed to install the protobuf-c finally.
just for the step configuration,set the environment CPLUS_INCLUDE_PATH to the needed header and make sure it is.

**Comment by wsky03** [comment]
@sympthom @KingElimy @markarsanious @dkopelove @ncopa 

hi, 

 i meet the same error as cross compile protobuf-c for vxworks.

the file command_line_interface.h exists at `/usr/include` ( or `/usr/local/include`, depends on your environment).

so, i set the enviroment `export PATH=$PATH:/usr/include`, and this make the problem resolved.

**Comment by meghalidhoble** [comment]
I have observed similar problem while building protobuf-c and found that it fails with latest version of protobuf (3.6.x). Hence I used the older version protobuf-2.6.1 and the ./configure worked file without any changes being done at configure.ac file. Hope this will help others too.

**Comment by kid1412hv** [comment]
configure file wants to check this file (command_line_interface.h) exists or not.
AC_CHECK_HEADERS([google/protobuf/compiler/command_line_interface.h

If you know where it is (It should exist if you compile protobuf before). Please add CPPFLAGS to ./configure
For example:  ./configure --host=$(TOOLCHAIN_PREFIX) --prefix=$(CURR_DIR) CPPFLAGS=-I$(CURR_DIR)/include LIBS=-L$(CURR_DIR)/lib; \

**Comment by renzheng0403** [comment]
> You need the protoc development headers. On ubuntu this package has the name libprotoc-dev.

Thanks，Solved my problem (on Ubuntu 20.04) Solved. libprotoc-dev installed `command_line_interface.h` in `/usr/include/google/protobuf/compiler`
