### ISSUE TITLE
can not cross compile libprotobuf-c ,show that it can not find  libproto.so

### ISSUE THREAD

**Issue by jackymail** [protobuf-c/protobuf-c#319]
when cross compile the libprotobuf-c ,and execute the make command,it always link the libproto.so
in the usr/local/bin directory,which is compiled with gcc. how to let  the protobuf-c use the cross compiled  libproto.so,  (I am using libprotobuf1.2.1).

**Comment by dota17** [comment]
Hi, @jackymail 
I also encountered this problem, the error message shows "error while loading shared libraries: libprotoc.so.9: cannot open shared object file: No such file or directory".
I  ran this command solved the problem:

export LD_LIBRARY_PATH=/usr/local/lib

Hope it can help you.

**Comment by lipnitsk** [comment]
OpenWrt builds this library for lots of platforms. Take a look [there](https://openwrt.org/packages/pkgdata/libprotobuf-c) for pointers.
