### ISSUE TITLE
Makefile gives error when running trying to make!

### ISSUE THREAD

**Issue by markarsanious** [protobuf-c/protobuf-c#321]
CXX      protoc-c/protoc_c_protoc_gen_c-c_bytes_field.o
protoc-c/c_bytes_field.cc: In member function ‘virtual void google::protobuf::compiler::c::BytesFieldGenerator::GenerateStructMembers(google::protobuf::io::Printer*) const’:
protoc-c/c_bytes_field.cc:104:24: error: ‘const class google::protobuf::FieldDescriptor’ has no member named ‘containing_oneof’
       if (descriptor_->containing_oneof() == NULL && FieldSyntax(descriptor_) =
                        ^
Makefile:1326: recipe for target 'protoc-c/protoc_c_protoc_gen_c-c_bytes_field.o' failed
make: *** [protoc-c/protoc_c_protoc_gen_c-c_bytes_field.o] Error 1

Does anyone know the reason for this? I have protobuf v2.5 installed correctly

**Comment by lipnitsk** [comment]
Please try with a more recent version of protobuf.
