### ISSUE TITLE
Launchpad PPA for protobuf-c (for use with Travis CI etc)

### ISSUE THREAD

**Issue by ringerc** [protobuf-c/protobuf-c#326]
Hi

I'm working with a protobuf-c project and I'm trying to add Travis-CI support, but the use of Ubuntu Trusty  there makes that impractical.

I don't see a Launchpad PPA for protobuf-c, only for protobuf its self (https://launchpad.net/~maarten-fonville/+archive/ubuntu/protobuf).

So I'm putting out a plea for anyone who's Launchpad-handy, in the hopes someone's interested.

(Feature/infratructure request, obviously)

**Comment by lipnitsk** [comment]
You should download and rebuild protobuf-c from source, or find way to install the package from Focal, if you need the latest and greatest.
