### ISSUE TITLE
Build configuration fails with protobuf 3.6.0

### ISSUE THREAD

**Issue by vahanara** [protobuf-c/protobuf-c#327]
Starting from version 3.6.0 protobuf requires C++11. Running configure on protobuf-c from release 1.3.0 fails on [command_line_interface.h] check due to "This file requires compiler and library support for the ISO 2011 standard. This support must be enabled with -std=c++11 or -std=gnu++11 compiler options." Seems same root cause as #317

**Comment by pravi** [comment]
@vahanara it seems the protobuf-c maintainer is missing, see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=901015#12 for a discussion on this issue.

> As I can't reach Robert for about nine months and I don't see any life sign from
> him either, protobuf-c definitely needs a new upstream maintainer with
> internal protobuf knowledge.
