### ISSUE TITLE
Repeated message field should be an array of struct

### ISSUE THREAD

**Issue by ccll** [protobuf-c/protobuf-c#329]
For following .proto code:
```
message Bar {
    ...
}

message Foo {
    repeated Bar bars = 1;
}
```

The generated type is an array of pointers (to struct Bar):
```
{
    ...
    size_t n_bars;
    Bar **bars;
    ...
}
```

This is unnecessary in C as there are no polymorphic pointers like in C++, and also very cache-unfriendly as the extra indirection.
I think a simple plain array of struct would be better, any thoughts? Or did I miss something?

**Comment by Xitsa** [comment]
When all your messages are references it simplifies construction of message from submessages:
for each message you will have one function which allocate memory and initialize it and then you just use it whenever appropriate.
as for cache-frienliness -- use arena allocator, it greatly makes life simpler.

**Comment by ccll** [comment]
@Xitsa Good point on the arena allocator. Thanks and closing!
