### ISSUE TITLE
Windows dll has not export protobuf_c_empty_string variable 

### ISSUE THREAD

**Issue by wosshzhb** [protobuf-c/protobuf-c#331]
In Windows environment， I  use macro PROTOBUF_C_USE_SHARED_LIB and PROTOBUF_C_EXPORT to build dll library，but the protobuf_c_empty_string variable has not be exported, should  the protobuf_c_empty_string variable add PROTOBUF_C__API ?

![20180727205945](https://user-images.githubusercontent.com/10632522/43322158-6d555d38-91e0-11e8-9f1b-0a6c5f551378.png)

**Comment by lipnitsk** [comment]
@edmonds do you think this is an issue? Seems like a valid case, since `protobuf_c_empty_string` is referenced inside the generated `.pb-c.c` code. Adding `PROTOBUF_C__API` to the `protobuf_c_empty_string` declaration should not affect the Linux builds in any way

**Comment by edmonds** [comment]
@lipnitsk If there is a pull request we can certainly evaluate it :man_shrugging: I personally have no experience with Windows development.

**Comment by lipnitsk** [comment]
@wosshzhb Can you submit a pull request? This change looks trivial, but I also have no means to test on Windows at this point.
