### ISSUE TITLE
Error while loading shared libraries: libprotobuf.so.17: no such file or directory

### ISSUE THREAD

**Issue by mharris3960** [protobuf-c/protobuf-c#336]
[Title]

**Comment by Avin-Techv** [comment]
i too get this error when installing tensorflow via make command

this is the error i get for this command

tensorflow/contrib/makefile/gen/bin/benchmark  --graph=$HOME/graphs/inception/tensorflow_inception_graph.pb

tensorflow/contrib/makefile/gen/bin/benchmark: error while loading shared libraries: libprotobuf.so.17: cannot open shared object file: No such file or directory

**Comment by sathyamoorthyrr** [comment]
found same error. any updates?

**Comment by fedemengo** [comment]
Same problem here, has anyone found a solution yet?

**Comment by lipnitsk** [comment]
`libprotobuf.so` is exported by the protobuf library, not protobuf-c. Please contact libprotobuf developers if you are still seeing issues.
