### ISSUE TITLE
Failed on building

### ISSUE THREAD

**Issue by hxingpax** [protobuf-c/protobuf-c#344]
## Output of make:

      CXX      t/t_generated_code2_cxx_generate_packed_data-test-full.pb.o
    t/generated-code2/cxx-generate-packed-data.cc: In function ‘void dump_test_unknown_fields()’:
    t/generated-code2/cxx-generate-packed-data.cc:1001:36: error: ‘Reflection’ in ‘class google::protobuf::Message’ does not name a type
       const google::protobuf::Message::Reflection *reflection = mess.GetReflection();
                                        ^~~~~~~~~~
    t/generated-code2/cxx-generate-packed-data.cc:1002:43: error: ‘reflection’ was not declared in this scope
       google::protobuf::UnknownFieldSet *fs = reflection->MutableUnknownFields(&mess);
                                               ^~~~~~~~~~
    t/generated-code2/cxx-generate-packed-data.cc:1002:43: note: suggested alternative: ‘sigaction’
       google::protobuf::UnknownFieldSet *fs = reflection->MutableUnknownFields(&mess);
                                               ^~~~~~~~~~
                                               sigaction
    Makefile:1524: recipe for target 't/generated-code2/t_generated_code2_cxx_generate_packed_data-cxx-generate-packed-data.o' failed
    make: *** [t/generated-code2/t_generated_code2_cxx_generate_packed_data-cxx-generate-packed-data.o] Error 1
    make: *** Waiting for unfinished jobs....

# System information:

    Linux xing-MacBookPro 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

# Protobuf version:

    libprotoc 3.6.1

Built from official protobuf source code.

**Comment by storyun** [comment]
You can see this pull request #342.

I already fixed this bug.
