### ISSUE TITLE
get warning when compile,  warning: ISO C90 forbids mixed declarations and code

### ISSUE THREAD

**Issue by dennisWind** [protobuf-c/protobuf-c#347]
protobuf-c/protobuf-c.c: In function ‘parse_oneof_member’:
protobuf-c/protobuf-c.c:2639:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
   const ProtobufCFieldDescriptor *old_field =
   ^
  CCLD     protobuf-c/libprotobuf-c.la

**Comment by lipnitsk** [comment]
This was fixed in b8cd15a84ffdf10d915b5b1a6331722a50a1470c
