### ISSUE TITLE
‘Reflection’ in ‘class google::protobuf::Message’ does not name a type

### ISSUE THREAD

**Issue by jasonclinx** [protobuf-c/protobuf-c#356]
Hi, I tried to `make` protobuf-c, using the latest protobuf repo and encountered the error below. It seems a namespacing issue. I checked [`message.h`](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/message.h) in protobuf repo, `Reflection` should be in the namespacing `google::protobuf`, instead of `google::protobuf::Message`. So I am wandering why the code in protobuf-c uses ` const google::protobuf::Message::Reflection`? 

```
  CXX    t/generated-code2/t_generated_code2_cxx_generate_packed_data-cxx-generate-packed-data.o
t/generated-code2/cxx-generate-packed-data.cc: In function ‘void dump_test_unknown_fields()’:
t/generated-code2/cxx-generate-packed-data.cc:1001:36: error: ‘Reflection’ in ‘class google::protobuf::Message’ does not name a type
   const google::protobuf::Message::Reflection *reflection = mess.GetReflection();
                                    ^
t/generated-code2/cxx-generate-packed-data.cc:1002:43: error: ‘reflection’ was not declared in this scope
   google::protobuf::UnknownFieldSet *fs = reflection->MutableUnknownFields(&mess);
                                           ^
make: *** [t/generated-code2/t_generated_code2_cxx_generate_packed_data-cxx-generate-packed-data.o] Error 1
```

**Comment by jasonclinx** [comment]
I saw the [issue#342](https://github.com/protobuf-c/protobuf-c/pull/342), which addressed the same issue but in Ubuntu and is already fixed according to the last reply of this issue.

I was building protobuf-c on RedHat6.4. This issue still remains.

**Comment by disdi** [comment]
Could somebody submit a patch for the same ?

**Comment by NickSong** [comment]
It doesn't work for me on Ubuntu 16.04.5

**Comment by ecmagalhaes** [comment]
How did you guys solved this issue?
Which file do I need to changed the code to use the namespace?

**Comment by Fullaxx** [comment]
I was able to get around this issue by disabling tests. I hope there is a code fix for this ins the future though.

./configure --disable-protoc
