### ISSUE TITLE
protoc-c don't generate has_ members

### ISSUE THREAD

**Issue by dr-begemot** [protobuf-c/protobuf-c#364]
protobuf declare file 'rpc.proto':
```
syntax = "proto3";
...
message PingRequest {
  string message = 1;
  int32 some_value = 2;   
}
...
```
In Makefile run:
_@protoc-c --c_out=./src ./proto/rpc.proto_

On libprotoc 3.0.0 protoc-c generate structure as:
```
struct  _PingRequest
{
  ProtobufCMessage base;
  char *message;
  protobuf_c_boolean has_some_value;
  int32_t some_value;
};

```
in new libprotoc 3.6.0 protoc-c gen structure as:
```
struct  _PingRequest
{
  ProtobufCMessage base;
  char *message;
  int32_t some_value;
};

```
Where is member 'has_some_value'???

**Comment by lipnitsk** [comment]
The `has_` fields do not get generated for proto3. See #228
