### ISSUE TITLE
no separate packing function for sub message

### ISSUE THREAD

**Issue by usergoodvery** [protobuf-c/protobuf-c#366]
Assuming I have the following schema:
message Outer {
    message Inner {
        optional uint32 id_inner  = 1;
    }
     optional uint32 id_outer  = 1;
 }

The compiler will create the type 'Outer__Inner' which is fine, but it doesn't generate a separate packing function for inner a la Outer__Inner_pack(...). Is that design feature?

**Comment by lipnitsk** [comment]
Duplicate of #240
