### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by xiaodaxia-2008** [protobuf-c/protobuf-c#370]
Building with Debian-9 with gcc 6.3.0, and get a failure, the build info is below:
 
CXX      protoc-c/protoc_c_protoc_gen_c-c_bytes_field.o
  CXX      protoc-c/protoc_c_protoc_gen_c-c_enum.o
  CXX      protoc-c/protoc_c_protoc_gen_c-c_enum_field.o
  CXX      protoc-c/protoc_c_protoc_gen_c-c_extension.o
  CXX      protoc-c/protoc_c_protoc_gen_c-c_field.o
  CXX      protoc-c/protoc_c_protoc_gen_c-c_file.o
  CXX      protoc-c/protoc_c_protoc_gen_c-c_generator.o
  CXX      protoc-c/protoc_c_protoc_gen_c-c_helpers.o
  CXX      protoc-c/protoc_c_protoc_gen_c-c_message.o
  CXX      protoc-c/protoc_c_protoc_gen_c-c_message_field.o
  CXX      protoc-c/protoc_c_protoc_gen_c-c_primitive_field.o
  CXX      protoc-c/protoc_c_protoc_gen_c-c_service.o
  CXX      protoc-c/protoc_c_protoc_gen_c-c_string_field.o
  CXX      protoc-c/protoc_c_protoc_gen_c-main.o
  CXXLD    protoc-c/protoc-gen-c
  GEN      t/test.pb-c.c
[libprotobuf WARNING google/protobuf/compiler/parser.cc:574] No syntax specified for the proto file: t/test.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
  GEN      t/test-full.pb-c.c
[libprotobuf WARNING google/protobuf/compiler/parser.cc:574] No syntax specified for the proto file: t/test-full.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
  GEN      t/test-optimized.pb-c.c
[libprotobuf WARNING google/protobuf/compiler/parser.cc:574] No syntax specified for the proto file: t/test-optimized.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
  GEN      t/test-full.pb.cc
[libprotobuf WARNING google/protobuf/compiler/parser.cc:574] No syntax specified for the proto file: t/test-full.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
  CXX      t/generated-code2/t_generated_code2_cxx_generate_packed_data-cxx-generate-packed-data.o
t/generated-code2/cxx-generate-packed-data.cc: In function ‘void dump_test_unknown_fields()’:
t/generated-code2/cxx-generate-packed-data.cc:1001:36: error: ‘Reflection’ in ‘class google::protobuf::Message’ does not name a type
   const google::protobuf::Message::Reflection *reflection = mess.GetReflection();
                                    ^~~~~~~~~~
t/generated-code2/cxx-generate-packed-data.cc:1002:43: error: ‘reflection’ was not declared in this scope
   google::protobuf::UnknownFieldSet *fs = reflection->MutableUnknownFields(&mess);
                                           ^~~~~~~~~~
Makefile:1524: recipe for target 't/generated-code2/t_generated_code2_cxx_generate_packed_data-cxx-generate-packed-data.o' failed
make: *** [t/generated-code2/t_generated_code2_cxx_generate_packed_data-cxx-generate-packed-data.o] Error 1

**Comment by edmonds** [comment]
Fixed in #369.
