### ISSUE TITLE
server_deserialize failed

### ISSUE THREAD

**Issue by morris2600** [protobuf-c/protobuf-c#371]
My client is Python, and server is protobuf-c/protobuf-c-rpc;
but when clint send messages to server,  there's no response at my server service functions,  when debuging by gdb ,  I find it return "PROTOBUF_C_RPC_PROTOCOL_STATUS_INCOMPLETE_BUFFER" at "server_deserialize" in protobuf-c-rpc-server.c ,  after "protobuf_c_rpc_data_buffer_peek"  was called :
  “  **protobuf_c_rpc_data_buffer_peek** (in_buffer, header, sizeof (header));
     payload->method_index = uint32_from_le (header[0]);
    message_length = uint32_from_le (header[1]);
     /* store request_id in whatever endianness it comes in */
    payload->request_id = header[2];
    if (in_buffer->size < sizeof (header) + message_length)
      **return PROTOBUF_C_RPC_PROTOCOL_STATUS_INCOMPLETE_BUFFER; ”**

As I know, protobuf-c-rpc add three int32 value at the header of message,  so I my question is :
1)  Is it compatible between python and protocbuf-c? 
2) how to fix this issue?

**Comment by lipnitsk** [comment]
Depending on the RPC header, there is a good chance that the python implementation is different from the default protobuf-c-rpc implementation. In that case, you would need to implement your own serialize/deserialize functions. protobuf-c-rpc allows for that flexibility
