### ISSUE TITLE
Cross compile error

### ISSUE THREAD

**Issue by edanla** [protobuf-c/protobuf-c#382]
Cross compile while executing “./configure --host=arm-oe-linux CC=arm-oe-linux-gnueabi-gcc CXX=arm-oe-linux-gnueabi-g++ --disable-protoc --prefix=/usr/local/protobuf-c-arm”，
Error logs are as follows:
configure:3445: arm-oe-linux-gnueabi-gcc -V >&5
 91 arm-oe-linux-gnueabi-gcc: error: unrecognized command line option '-V'
 92 arm-oe-linux-gnueabi-gcc: fatal error: no input files
 93 compilation terminated.
 94 configure:3456: $? = 1
 95 configure:3445: arm-oe-linux-gnueabi-gcc -qversion >&5
 96 arm-oe-linux-gnueabi-gcc: error: unrecognized command line option '-qversion'; did you mean '--version'?
 97 arm-oe-linux-gnueabi-gcc: fatal error: no input files
 98 compilation terminated.
 99 configure:3456: $? = 1
100 configure:3476: checking whether the C compiler works
101 configure:3498: arm-oe-linux-gnueabi-gcc  -O2 -Wa,--noexecstack -fexpensive-optimizations -frename-register    s -fomit-frame-pointer -ftree-vectorize   -finline-functions -finline-limit=64   -Wno-error=maybe-uninitial    ized -Wno-error=unused-result  -include quectel-features-config.h   -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-n    eeded conftest.c  >&5
102 /home/edan/AG35/ql-ol-sdk/ql-ol-crosstool/sysroots/x86_64-oesdk-linux/usr/bin/arm-oe-linux-gnueabi/../../li    bexec/arm-oe-linux-gnueabi/gcc/arm-oe-linux-gnueabi/6.4.0/real-ld: error: /tmp/ccoBBUgd.o uses VFP register     arguments, output does not
103 collect2: error: ld returned 1 exit status
104 configure:3502: $? = 1
105 configure:3540: result: no
106 configure: failed program was:

**Comment by ubx-luis** [comment]
Did you find the answer to this?

**Comment by lipnitsk** [comment]
OpenWrt builds this library for lots of platforms. Take a look [there](https://openwrt.org/packages/pkgdata/libprotobuf-c) for pointers.
