### ISSUE TITLE
Cross compilation can't find the header file “ac_nonexistent.h”

### ISSUE THREAD

**Issue by edanla** [protobuf-c/protobuf-c#383]
Executing "./configure" produces the following error:
configure:4907: /home/edan/AG35/ql-ol-sdk/ql-ol-crosstool/sysroots/x86_64-oesdk-linux/usr/bin/arm-oe-linux     -gnueabi/arm-oe-linux-gnueabi-gcc -mfloat-abi=hard -E  conftest.c
  conftest.c:11:28: fatal error: ac_nonexistent.h: No such file or directory
  #include <ac_nonexistent.h>

**Comment by lipnitsk** [comment]
OpenWrt builds this library for lots of platforms. Take a look [there](https://openwrt.org/packages/pkgdata/libprotobuf-c) for pointers.
