### ISSUE TITLE
protobuf 2.5  can not set string value correct on AIX 6.1 

### ISSUE THREAD

**Issue by horizon999** [protobuf-c/protobuf-c#385]
when I set seffdate  and sexpdate , in the end ,sexpdate and seffdate  always be equal (value is 20190617000000)   ,so I  dbx the program ，the pointer address _seffdate  and _sexpdate is same ，I  don't  know why .
---------------platform----------------
AIX 6.1.0.0
---------------code----------------
<testclient>
::google::protobuf::PbUpdBalanceDetailCmd * pbReqbody = new ::google::protobuf::PbUpdBalanceDetailCmd();
 google::protobuf::PbBalanceDetail * popbbaledetail = pbReqbody->add_opbbaledetail();
    popbbaledetail->set_lacctbalanceid(1);
	popbbaledetail->set_inewoldflag(0);
	popbbaledetail->set_istatuscd(2);
    popbbaledetail->set_seffdate("20190613000000");
	popbbaledetail->set_sexpdate("20190617000000");
------------------------------------------------------------------------- 
<PbBalanceDetail >
// required int64 lAcctBalanceID = 1;
  inline bool has_lacctbalanceid() const;
  inline void clear_lacctbalanceid();
  static const int kLAcctBalanceIDFieldNumber = 1;
  inline ::google::protobuf::int64 lacctbalanceid() const;
  inline void set_lacctbalanceid(::google::protobuf::int64 value);
  
  // required int32 iNewOldFlag = 2;
  inline bool has_inewoldflag() const;
  inline void clear_inewoldflag();
  static const int kINewOldFlagFieldNumber = 2;
  inline ::google::protobuf::int32 inewoldflag() const;
  inline void set_inewoldflag(::google::protobuf::int32 value);
  
  // required int32 iStatusCD = 3;
  inline bool has_istatuscd() const;
  inline void clear_istatuscd();
  static const int kIStatusCDFieldNumber = 3;
  inline ::google::protobuf::int32 istatuscd() const;
  inline void set_istatuscd(::google::protobuf::int32 value);
  
  // required bytes sEffDate = 4;
  inline bool has_seffdate() const;
  inline void clear_seffdate();
  static const int kSEffDateFieldNumber = 4;
  inline const ::std::string& seffdate() const;
  inline void set_seffdate(const ::std::string& value);
  inline void set_seffdate(const char* value);
  inline void set_seffdate(const void* value, size_t size);
  inline ::std::string* mutable_seffdate();
  inline ::std::string* release_seffdate();
  
  // required bytes sExpDate = 5;
  inline bool has_sexpdate() const;
  inline void clear_sexpdate();
  static const int kSExpDateFieldNumber = 5;
  inline const ::std::string& sexpdate() const;
  inline void set_sexpdate(const ::std::string& value);
  inline void set_sexpdate(const char* value);

**Comment by lipnitsk** [comment]
This looks like C++ code, this project generates and operates on C code. Closing as invalid issue.
