### ISSUE TITLE
Protocol v3 not working well

### ISSUE THREAD

**Issue by wuhanstudio** [protobuf-c/protobuf-c#386]
Hello, 

I'm a master student from China trying to decode protobuf on embedded devices.

I found some issues pertaining to examples on the [Wiki](https://github.com/protobuf-c/protobuf-c/wiki/Examples) page.

When I defined a protov2 file:

```
syntax = "proto2";
message AMessage {
  required int32 a=1; 
  optional int32 b=2;
}
```

It returned with some warnings:

```
amessage.proto:5:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, 
as fields are 'optional' by default.
amessage.proto: Required fields are not allowed in proto3.
```

So I switched to proto v3 syntax:

```
syntax = "proto3";

message AMessage {
  int32 a=1; 
  int32 b=2;
}
```

In this way, the example will not serialize variable **a** in message since **msg.has_a=1** is not set in the example:

```
#include <stdio.h>
#include <stdlib.h>
#include "amessage.pb-c.h"

int main (int argc, const char * argv[]) 
{
  AMessage msg = AMESSAGE__INIT; // AMessage
  void *buf;                     // Buffer to store serialized data
  unsigned len;                  // Length of serialized data
  
  if (argc != 2 && argc != 3)
  {   // Allow one or two integers
    fprintf(stderr,"usage: amessage a [b]\n");
    return 1;
  }
  
  msg.a = atoi(argv[1]);
  if (argc == 3) { msg.has_b = 1; msg.b = atoi(argv[2]); }
  len = amessage__get_packed_size(&msg);
  
  buf = malloc(len);
  amessage__pack(&msg,buf);
  
  fprintf(stderr,"Writing %d serialized bytes\n",len); // See the length of message
  fwrite(buf,len,1,stdout); // Write to stdout to allow direct command line piping
  
  free(buf); // Free the allocated serialized buffer
  return 0;
}
```
Does this mean I need to set "msg.has_x=1" manually for every attribute defined in Proto V3 which may be a little cumbersome?

Thanks for your time.

**Comment by acozzette** [comment]
Proto3 doesn't have field presence for singular primitive fields, or in other words there is no distinction between an int32 field being set to 0 and being unset.

**Comment by wuhanstudio** [comment]
> Proto3 doesn't have field presence for singular primitive fields, or in other words there is no distinction between an int32 field being set to 0 and being unset.

Thanks for your help.

Indeed, without **msg.has_a=1**,  **message.a** will always be 0, even if there is **msg.a = atoi(argv[1]);**
