### ISSUE TITLE
Need to build a Universal Protoc-c Compiler

### ISSUE THREAD

**Issue by naveenkumart28** [protobuf-c/protobuf-c#390]
Hi,
       I need to build a universal protoc-c compiler for i386 similar to this one,

https://github.com/microsoft/PLCrashReporter/blob/develop/Dependencies/protobuf-2.0.3/bin/protoc-c

based on Protobuf-3.6 and Protobuf-c 1.3.
 When i generate protoc-c, it depends on **libprotobuf.xx.dylib**, but the above attached protoc-c from 2.0.3 doesnt require libprotobuf.dylib

How to generate the protoc-c compiler which generates only .h and .c given a proto path?
Is it possible to generate it, independent of libprotobuf?

**Comment by edmonds** [comment]
Here's the discussion list: https://groups.google.com/forum/#!forum/protobuf-c.
