### ISSUE TITLE
OSS-Fuzz integration

### ISSUE THREAD

**Issue by guidovranken** [protobuf-c/protobuf-c#393]
Hi there,

I've written fuzzers for protobuf-c and [they are ready to be integrated into OSS-Fuzz](https://github.com/google/oss-fuzz/pull/2772).
For more information OSS-Fuzz, please see the FAQ: https://google.github.io/oss-fuzz/faq/

Are any of the maintainers of this software willing to receive automated reports of issues found by OSS-Fuzz?

Thanks

**Comment by guidovranken** [comment]
Ping. If interested, please give me e-mail addresses (must be linked to Google accounts) of the maintainers. Thanks.

**Comment by lipnitsk** [comment]
For me it is first_name.last_name@gmail.com (see my profile for name).

**Comment by guidovranken** [comment]
Thank you @lipnitsk but please be aware that your e-mail address will be stored publicly in project.yaml: https://github.com/google/oss-fuzz/blob/78fc3a9a6071e43ff53339211abab4d3d243c4b0/projects/protobuf-c/project.yaml

Is that OK?

**Comment by lipnitsk** [comment]
Actually, if you don't mind having your name there since you probably have more interest (and maybe time) in this, that works for me. You are welcome to report any issues found here. I'm gonna go ahead and close this issue.
