### ISSUE TITLE
Call protobuf_c_message_pack_to_buffer recursively for nested messages to save copies

### ISSUE THREAD

**Issue by mrksngl** [protobuf-c/protobuf-c#394]
In `required_field_pack_to_buffer` (maybe also others), there is `case PROTOBUF_C_TYPE_MESSAGE` where the nested message is first encoded into `simple_buffer_scratch` and then this temporary buffer is appended to the user supplied `buffer`.

Now my alternative way is
1) determine the packed size of the nested message by means of `protobuf_c_message_get_packed_size` and append that size to the buffer,
2) then call `protobuf_c_message_pack_to_buffer` recursively with the nested message and the same `buffer`.

Con / Pro:
 * Con: In my suggestion, we have to descent twice: once for the count, once for encoding. In the current implementation, counting and encoding is done in one step, so we have to descent only once.
 * Pro: saves a copy. Not only a single one, but in the current implementation, there is a copy on each nesting level. E.g. the contents of a message that is on level N (counting from the top level), is copied N-1 times in total.

From my perspective, descending twice should be more performant than copying.

I also created a patch, and it worked for a small example. Would need more testing, but I could file a merge request if interested.

**Comment by mrksngl** [comment]
Bit more background: using this, fields declared with type `bytes` will actually be passed unchanged to the append function.

So let's assume you have such a field in your (nested) message and you expect there is a lot of data in it, you can store a pointer to those data in your buffer structure.
When the `data` pointer passed to the append callback and then matches your stored pointer (and my suggestion in this issue ensures this), you can use references instead of copies.

I use a `grpc_slice_buffer` to actually buffer data, so I can use `grpc_slice_new`, which will not copy the data.
This can be used for implementing real zero copy, at least for a selected set of fields.
Hacky, but performant ;)

I can provide some more code examples if wanted.

**Comment by lipnitsk** [comment]
It would be helpful if you could run some benchmarks to confirm that your change improves performance on different messages with varying nesting levels. Of course, the code, covered with some test cases would also be needed if you wanted to have it merged upstream :)

**Comment by mrksngl** [comment]
Of course, yes. I was just thinking that I maybe missed something obvious -- so if you were like "oh, that's a bad idea because..." there would be no reason for code ;)
Long story short: [this commit](https://github.com/SeRoSystems/protobuf-c/commit/7618b08c309bd646852ae9434f050df1fd32b01c) does the job. I did some benchmarks on an embedded arm device and there it did a great job. I'll supply actual numbers when I'm at work again.

But then again, I have to admit it was a quite long message, especially embedding a large repeated field (800 fixed32 iirc) inside. One may argue that protobuf was not designed for long messages ([reference](https://developers.google.com/protocol-buffers/docs/techniques)), so it should definitely be tested on smaller messages.

**Comment by mrksngl** [comment]
Ok, I still cannot access the numbers I referred to, but generated some new.

There, I defined a message `Test` having a `repeated fixed32` which was filled with 0,1,10,100,1000 or 10000 elements. On the wire, this repeated field dominates the overall message size, i.e. results about `N*4` bytes when serialized.

Then `Test` was nested in another message `Nest1`, which was nested in `Nest2` and this again was nested into `Nest3`. On the wire, this (admittedly: quite flat) nesting is not adding much overhead.

So I had different nesting levels (0-3) and different message sizes, controlled by the size of the repeated field.
I varied those parameters, serialized the resulting message a lot of times and determined average computation time.

Results:
 * for small messages, it does not make a measurable difference, i.e. descending twice is not adding overhead. I suppose that overhead of descending for determining the length is compensated by the overhead of copying.
 * for large messages (>1000 elements in the array), it can be observed that runtime of the upstream version has a linear dependency in the nesting level. Having my patch applied, runtime stays constant. It must be noted, however, that the message structure is quite flat, so the nesting level has little impact on determining the message length.

My (tentative) conclusion: runtime improvements depends on the nesting level on which there is a submessage which dominates the overall message size. At least on my machine, improvements are visible if there is a submessage on some nesting level >0 whose size is >4k.

Any suggestions for more (meaningful) runtime comparisons?

**Comment by lipnitsk** [comment]
> Any suggestions for more (meaningful) runtime comparisons?
I don't have any. I think you have done a good amount of testing to show that the change benefits your test case while not hurting performance for small messages.

Based on your results, it does not look like the change hurts performance measurably. It also only affects the `pack_to_buffer` path and removes the dependency on `ProtobufCBufferSimple`, which I like. Can you open a PR into the `next` branch with your change?
