### ISSUE TITLE
How do I use the .proto generated .c and .h files in a CLion project? "Undefined reference"

### ISSUE THREAD

**Issue by BBlayne** [protobuf-c/protobuf-c#404]
Hello, I am trying to use protobuf with a  C project (Not C++) together with ZeroMQ.

These are the errors:
```
undefined reference to `protobuf_c_message_get_packed_size'
undefined reference to `protobuf_c_message_pack'
undefined reference to `protobuf_c_message_pack_to_buffer'
undefined reference to `protobuf_c_message_unpack'
undefined reference to `protobuf_c_message_free_unpacked'
```
My CMakeLists.txt
```
cmake_minimum_required(VERSION 3.15)
project(zmq_client_project C)

set(CMAKE_C_STANDARD 99)
include_directories(${CMAKE_CURRENT_BINARY_DIR})


## load in pkg-config support
find_package(PkgConfig)
## use pkg-config to get hints for 0mq locations
pkg_check_modules(PC_ZeroMQ QUIET zmq)

## use the hint from above to find where 'zmq.hpp' is located
find_path(ZeroMQ_INCLUDE_DIR
        NAMES zmq.hpp
        PATHS ${PC_ZeroMQ_INCLUDE_DIRS}
        )

## use the hint from about to find the location of libzmq
find_library(ZeroMQ_LIBRARY
        NAMES zmq
        PATHS ${PC_ZeroMQ_LIBRARY_DIRS}
        )
set(PROJECT_HEADERS
        amessage.pb-c.h
        )
set(SOURCE_FILES main.c amessage.pb-c.c)

add_executable(zmq_client_project main.c)

## add the include directory to our compile directives
target_include_directories(zmq_client_project PUBLIC ${ZeroMQ_INCLUDE_DIR})
## at the 0mq library to our link directive
target_link_libraries(zmq_client_project PUBLIC ${ZeroMQ_LIBRARY})
```

I don't really know what I'm doing. I'm a Windows Visual Studios sort of developer but I am currently stuck with Ubuntu/CLion for reasons.

**Comment by dr-begemot** [comment]
You must first create .c/.h files from .proto-files
`protoc-c --c_out=$(SRC) $(PROTOFILES)`
where $(SRC) - your dir with sources (main.c etc), $(PROTOFILES) - your set .proto-files

**Comment by BBlayne** [comment]
Okay but the tutorial said I could've generated them separately and then use the resulting files in my project. Isn't the error that the protobuf functions it can't find? I generated the .c/.h files separately and dropped them in the folder. Is this not a valid use?

Also how do I include the library to my project? I am using Clion as my IDE on Ubuntu and it has a CMakeLists.txt file, I have tried googling how to do this but nothing seems to be working.

**Comment by BBlayne** [comment]
I have solved my problem, it turned out most of the Link Library examples for CMake were overly complicated and all that was needed was this:

```
cmake_minimum_required(VERSION 3.15)
project(protobuf_c_example C)

set(CMAKE_C_STANDARD 99)

set(PROJECT_HEADERS amessage.pb-c.h)
set(SOURCE_FILES main.c amessage.pb-c.c)

add_executable(protobuf_c_example ${SOURCE_FILES})

## link directive
target_link_libraries(protobuf_c_example protobuf-c)
```

I hope this solved this problem for any future person who stumbles on this problem.
