### ISSUE TITLE
How to build a separate protoc-c binary file without relying on any other libraries?

### ISSUE THREAD

**Issue by xuning0** [protobuf-c/protobuf-c#411]
I have tried to build according to documentation, but I just got a `protoc-gen-c`. It looks to depend on `protobuf` and `libprotoXXX.dylib` on my machine.

How can I  get a separate protoc-c binary, which can be copied to any other machines and exec `protoc-c --c_out=xxxxxxx` directly?

**Comment by xuning0** [comment]
It sounds weird, but I use our company's common CI environment, so I may only add the `protoc-c` binary file to my project.

**Comment by lipnitsk** [comment]
No, protoc-c requires libprotobuf.
