### ISSUE TITLE
`bool` compatibility with other integer types

### ISSUE THREAD

**Issue by dddzzz18** [protobuf-c/protobuf-c#440]
According to https://developers.google.com/protocol-buffers/docs/proto3#updating:

> int32, uint32, int64, uint64, and bool are all compatible

though if you deserialize a packed bool with a value greater than 1, it will trigger this error message: "bad packed repeated value".
https://github.com/protobuf-c/protobuf-c/blob/master/protobuf-c/protobuf-c.c#L2846

**Comment by lipnitsk** [comment]
But if you change the type in the proto file to int32, uint32, int64, or uint64 and decode the same payload it should work, which is what the message above states. I don't like the idea of putting non-boolean values into `protobuf_c_boolean`. I don't think we will make any changes for this.

**Comment by lipnitsk** [comment]
Although I suppose we could entertain unpacking and truncating the value to 0 or 1, but without a parsing error.
