### ISSUE TITLE
Compiling with msvc

### ISSUE THREAD

**Issue by miragias** [protobuf-c/protobuf-c#447]
Hello I have been trying to compile protobuf-c with msvc. Forgive my probably stupid question but I am still getting acquainted with some of the stuff. So what I have been trying:

Using cmake and pressing configure : 
```
Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
The C compiler identification is MSVC 19.27.29111.0
The CXX compiler identification is MSVC 19.27.29111.0
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Check if the system is big endian
Searching 16 bit integer
Looking for sys/types.h
Looking for sys/types.h - found
Looking for stdint.h
Looking for stdint.h - found
Looking for stddef.h
Looking for stddef.h - found
Check size of unsigned short
Check size of unsigned short - done
Searching 16 bit integer - Using unsigned short
Check if the system is big endian - little endian
C:/Users/ioann/Desktop/protobuf-c
Found Protobuf: C:/Users/ioann/Desktop/vcpkg/packages/protobuf_x86-windows/lib/libprotobuf.lib (found version "3.13.0") 
Configuring done
```
![compile](https://user-images.githubusercontent.com/13620491/96935438-ba838f00-14cc-11eb-8849-e9a5b6862fa2.PNG)

After I get the generated sln and open it and try to build all I get these link errors:
![linkerrors](https://user-images.githubusercontent.com/13620491/96935695-45fd2000-14cd-11eb-9313-de24bb2f5800.PNG)

`Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: bool __cdecl google::protobuf::FieldOptions::has_packed(void)const " (__imp_?has_packed@FieldOptions@protobuf@google@@QEBA_NXZ) referenced in function "protected: void __cdecl google::protobuf::compiler::c::FieldGenerator::GenerateDescriptorInitializerGeneric(class google::protobuf::io::Printer *,bool,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const " (?GenerateDescriptorInitializerGeneric@FieldGenerator@c@compiler@protobuf@google@@IEBAXPEAVPrinter@io@45@_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@2@Z)	protoc-gen-c	C:\Users\ioann\Desktop\MyCoolBuild\c_field.obj	1	
`

So from my understanding the fact that Protobuf_SRC_ROOT_FOLDER_NOT_FOUND which happens during the generate is where I should be passing the path to this linked library which after the generate will pass it into my solution correct? The question is which path do I add there? I tried cloning the protobuf-3.13.x from github and using this path : 

> C:\Users\ioann\Desktop\protobuf-3.13.x\src
but I still get these errors. I am probably missing something obvious.

**Comment by miragias** [comment]
Hi again, so I am probably trying to make a project for the wrong platform. I switched my configuration from x64 to win32. 
Made double sure that I also have the correct libraries (redownloaded them with vcpkg via vcpkg install protobuf). 
And I still have one linker error when trying to build: This time I am getting only this one linker error (in contrast with the above which I had 100+). 


> Severity	Code	Description	Project	File	Line	Suppression State
> Error	LNK2019	unresolved external symbol "__declspec(dllimport) const google::protobuf::compiler::c::CGenerator::`vftable'" (__imp_??_7CGenerator@c@compiler@protobuf@google@@6B@) referenced in function "public: __thiscall google::protobuf::compiler::c::CGenerator::CGenerator(void)" (??0CGenerator@c@compiler@protobuf@google@@QAE@XZ)	protoc-gen-c	C:\Users\ioann\Desktop\MyCoolBuild2\c_generator.obj	1	

My libraries seem to be included into the project and are the correct version (x86). 
![unresolved](https://user-images.githubusercontent.com/13620491/97034259-4d740600-156d-11eb-977b-b847da180e7b.PNG)

**Comment by lipnitsk** [comment]
This does not look like a bug to me. Please use the mailing list or other resources to ask questions.
