### ISSUE TITLE
unresolved external symbol (CGenerator) with Visual Studio 2017

### ISSUE THREAD

**Issue by jmckenna** [protobuf-c/protobuf-c#458]
- compiled protobuf-3.15.0-rc2 with `-DBUILD_SHARED_LIBS=ON` (yes I must have a DLL build, not static)
- configured protobuf-c-1.3.3 with `ADD_DEFINITIONS(-DPROTOBUF_USE_DLLS)` in CMakeLists.txt, and set `-DBUILD_SHARED_LIBS=ON`
- compile (protobuf-c-1.3.3) fails, with 1 unresolved external symbol error message:
```
Creating library protoc-gen-c.lib and object protoc-gen-c.exp
main.cc.obj : warning LNK4217: locally defined symbol ??0CGenerator@c@compiler@protobuf@google@@QAE@XZ (public: __thiscall google::protobuf::compiler::c::CGenerator::CGenerator(void)) imported in function _main
main.cc.obj : warning LNK4217: locally defined symbol ??1CGenerator@c@compiler@protobuf@google@@UAE@XZ (public: virtual __thiscall google::protobuf::compiler::c::CGenerator::~CGenerator(void)) imported in function _main
c_generator.cc.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) const google::protobuf::compiler::c::CGenerator::`vftable'" (__imp_??_7CGenerator@c@compiler@protobuf@google@@6B@) referenced in function "public: __thiscall google::protobuf::compiler::c::CGenerator::CGenerator(void)" (??0CGenerator@c@compiler@protobuf@google@@QAE@XZ)
protoc-gen-c.exe : fatal error LNK1120: 1 unresolved externals
```

This appears similar to issue reported through https://github.com/protobuf-c/protobuf-c/issues/447

**Comment by lipnitsk** [comment]
Still looks like a protobuf issue to me - are you sure you built all the libraries, for example, LIBPROTOC?

**Comment by jmckenna** [comment]
Yes, protobuf-c cmake is configured to point to those libs, as:
```
-DProtobuf_LIBRARY="%PROTOBUFDIR%\cmake\build\install\lib\libprotobuf.lib" ^
-DProtobuf_PROTOC_LIBRARY="%PROTOBUFDIR%\cmake\build\install\lib\libprotoc.lib" ^
-DProtobuf_LITE_LIBRARY="%PROTOBUFDIR%\cmake\build\install\lib\libprotobuf-lite.lib"
```

**Comment by jmckenna** [comment]
I think the first warning is a sign of things to come (the missing symbol):
```
main.cc.obj : warning LNK4217: locally defined symbol ??0CGenerator@c@compiler@protobuf@google@@QAE@XZ (public: __thiscall google::protobuf::compiler::c::CGenerator::CGenerator(void)) imported in function _main
```
That CGenerator() function is not from libprotobuf, but instead defined in c_generator.cc

**Comment by jmckenna** [comment]
(if I hadn't build and pointed to those libs properly, I would get hundreds of missing external symbols (as the person in ticket #447 noticed)  Now it is down to this one missing symbol.   Hmmmmm

**Comment by jmckenna** [comment]
I wonder if all that function is missing is the `dllexport_decl_(dllexport_decl)` declaration, hmmm

**Comment by jmckenna** [comment]
Solved.   This error can be fixed by adding the following into /protoc-c/c_generator.h around line#71 :
```
#define LIBPROTOC_EXPORT __declspec(dllexport)
```
That will now export the CGenerator class to the DLL, so that mysterious external symbol from protobuf-c can be loaded.

(it only took me 2 days to fix this, ha, yikes)  Hopefully this helps someone else someday, as they google and come here :)  

cc @miragias

cheers from the east coast of Canada.

**Comment by lipnitsk** [comment]
Thanks for triaging it. Since I have no easy way of testing it, would you mind testing the following branch for me:
https://github.com/protobuf-c/protobuf-c/tree/issue-458

**Comment by jmckenna** [comment]
Verified locally.
