### ISSUE TITLE
Static Build Instruction?

### ISSUE THREAD

**Issue by aviezab** [protobuf-c/protobuf-c#460]
I have successfully compiled [libprotobuf](http:://github.com/protocolbuffers/protobuf/tree/master/src) used for this project as static library.
However, I don't find any documentation regarding protobuf-c to be compiled as static library.

Can We compile the protobuf-c as static library?
Please help, thanks.

**Comment by lipnitsk** [comment]
libprotobuf-c.a is built with autotools or with cmake by default, so I don't understand the problem.
