### ISSUE TITLE
What is the purpose of the autogenerated c_name fields?

### ISSUE THREAD

**Issue by therealprof** [protobuf-c/protobuf-c#487]
I'm seeing huge autogenerated strings in the `c_name` fields which bloat generated binaries but not a single use anywhere in `libprotobuf-c`.

What exactly is the purpose of them?
Can we get rid of them?
Maybe by adding a `--strip` option to `protoc-c` if they're deemed useful for some exotic use case?

**Comment by lipnitsk** [comment]
You can use `option optimize_for = CODE_SIZE;` in your proto file to suppress string generation

**Comment by therealprof** [comment]
It's not my proto files but those published by others. Code generation should really be controllable by the user and not by the publisher of the files who cannot know how they will be used.

But thanks for the tip.
