### ISSUE TITLE
uninitialized variable compile error with GCC 10.3

### ISSUE THREAD

**Issue by yenytran** [protobuf-c/protobuf-c#490]
file: protobuf-c/protobuf-c.c, line 3158: size_t pref_len;

test -f 'src/protosrc/protobuf-c/protobuf-c.c:3153:26: error: ‘pref_len’ may be used uninitialized in this function [-Werror=maybe-uninitialized] 3153 | tmp.length_prefix_len = pref_len;

**Comment by edmonds** [comment]
Cannot reproduce with `gcc-10 (Debian 10.5.0-1) 10.5.0`. Probably a regression in gcc.
