### ISSUE TITLE
import in protobuf-c.proto causes 'file not found' error with Visual Studio 2019

### ISSUE THREAD

**Issue by jmckenna** [protobuf-c/protobuf-c#491]
- similar setup to my old issue #458 
- but now using protobuf-c 1.4.0 release
- error during compile with CMake:
```
Generating protobuf-c/protobuf-c.pb.cc, protobuf-c/protobuf-c.pb.h
  google/protobuf/descriptor.proto: File not found.
  protobuf-c/protobuf-c.proto:31:1: Import "google/protobuf/descripto
  r.proto" was not found or had errors.
  protobuf-c/protobuf-c.proto:60:8: "google.protobuf.FileOptions" is
  not defined.
  protobuf-c/protobuf-c.proto:75:8: "google.protobuf.MessageOptions"
  is not defined.
  protobuf-c/protobuf-c.proto:84:8: "google.protobuf.FieldOptions" is
   not defined.
```
- solution is to edit /build-cmake/CMakeLists.txt and add the missing `-I${PROTOBUF_INCLUDE_DIR}` parameter for the protoc executable (on line#96) such as:
```
ARGS --cpp_out ${CMAKE_BINARY_DIR} -I${MAIN_DIR} -I${PROTOBUF_INCLUDE_DIR} ${MAIN_DIR}/protobuf-c/protobuf-c.proto)
```

**Comment by aditi16690** [comment]
Hi @jmckenna , I could resolve this issue by including the directory :https://github.com/protocolbuffers/protobuf/tree/master/src/google/ into the current source directory. Hope it helps.

**Comment by jmckenna** [comment]
for the record, this fix ( edit /build-cmake/CMakeLists.txt and add the missing `-I${PROTOBUF_INCLUDE_DIR}` parameter) works great with the 1.4.1 release.

**Comment by jmckenna** [comment]
confirmed this fix in the `next` branch, thanks!
