### ISSUE TITLE
Crash during unpack

### ISSUE THREAD

**Issue by amarkevich** [protobuf-c/protobuf-c#494]
protobuf-c 1.4.0

Model:

```
syntax = "proto3";

enum mode_e
{
	MODE_IN = 0;
}

message mode_in
{
	uint32 value = 1;
}

message cfg
{
	mode_e mode = 1;

	oneof mode_cfg
	{
		mode_in in = 2;
	}
}

message node
{
	repeated cfg cfg = 1;
}
```

Code:
```
	ModeIn mode_in = MODE_IN__INIT;

	Cfg cfg = CFG__INIT;

	cfg.in = &mode_in;
	cfg.mode_cfg_case = CFG__MODE_CFG_IN;

	Cfg *pcfg = &cfg;

	Node node = NODE__INIT;
	node.cfg = &pcfg;
	node.n_cfg = 1;

	size_t len = node__get_packed_size(&node);
	uint8_t buf[len];
	node__pack(&node, buf);

	Node *pnode = node__unpack(NULL, len, buf);
	if (pnode) {
		node__free_unpacked(pnode, NULL);
	}
```

Actual: `node__unpack` crashed.

**Comment by amarkevich** [comment]
initial stack size 2048; works in case increased to 4096.

**Comment by lipnitsk** [comment]
> initial stack size 2048; works in case increased to 4096.

I think you answered your own question. Unless this is a large regression, I don't think this is a bug - the protobuf-c library needs sufficient stack space to work.

**Comment by amarkevich** [comment]
4 *bytes* packed data require 4k stack size?

**Comment by lipnitsk** [comment]
If there is an obvious inefficiency, feel free to propose a patch to improve it.
