### ISSUE TITLE
.proto file help

### ISSUE THREAD

**Issue by jahidhasanlinix** [protobuf-c/protobuf-c#495]
I am getting an error whole running .py file, I do have .proto file in the same folder. May I know how can I run .proto file? I never used this, but seems this .proto is important to execute my .py code. Any help

  File "server.py", line 3, in <module>
    import ipc_msg_pb2
ModuleNotFoundError: No module named 'ipc_msg_pb2'

**Comment by edmonds** [comment]
protobuf-c is not https://github.com/protocolbuffers/protobuf
