### ISSUE TITLE
unsigned integer overflow

### ISSUE THREAD

**Issue by steed717** [protobuf-c/protobuf-c#499]
Bug: len - pref_len will cause integer overlow.
Sugested fix below:

diff --git a/protobuf-c/protobuf-c.c b/protobuf-c/protobuf-c.c
index ad1bdb1..fe5ae91 100644
--- a/protobuf-c/protobuf-c.c
+++ b/protobuf-c/protobuf-c.c
@@ -2604,10 +2604,13 @@ parse_required_member(ScannedMember *scanned_member,
                        return FALSE;

                def_mess = scanned_member->field->default_value;
-               subm = protobuf_c_message_unpack(scanned_member->field->descriptor,
+               if (len > pref_len)
+                       subm = protobuf_c_message_unpack(scanned_member->field->descriptor,
                                                 allocator,
                                                 len - pref_len,
                                                 data + pref_len);
+               else
+                       subm = NULL;

                if (maybe_clear &&
                    *pmessage != NULL &&

**Comment by steed717** [comment]
can any review to be done with this issue ???

**Comment by steed717** [comment]
is this project still active???

**Comment by ghenry** [comment]
The forum looks non-responsive - https://groups.google.com/g/protobuf-c

I'm not sure who the project leads are or if they are looking for help?

**Comment by maa04** [comment]
According to the code analysis, (len >= pref_len) is always true, and (len - pref_len) will not be less than 0. Should it be a REAL BUG?
