### ISSUE TITLE
how we can parse proto file if it having "." and "-" sign

### ISSUE THREAD

**Issue by dhivarprajakta** [protobuf-c/protobuf-c#510]
I create one proto file using java and another using python when I put "." and "-" sign in proto file message field name it shows error that is "missing field number". I m not able to parse that file. and if proto file not accept this character please can share list of character those proto file not accept. or give any Referenced for building proto file in java and python and how to parse that file.

**Comment by edmonds** [comment]
protobuf-c is not https://github.com/protocolbuffers/protobuf
