### ISSUE TITLE
Undefined reference when linking protobuf-c statically

### ISSUE THREAD

**Issue by KAction** [protobuf-c/protobuf-c#533]
When trying to statically build protobuf-c, I get bunch of undefined references to C++ symbols [build log](https://gist.github.com/b56e741c94994ce0a236b4e93de7c01a).

 It has to do with order in which link flags are passed: `-lprotobuf -lprotoc` is bad, `-lprotoc -lprotobuf` is good. Simple
```
sed -i 's,-lprotoc,-lprotoc -lprotobuf,' Makefile.am
```
seems to solve the problem without affecting dynamic build.

Link to distribution issue: https://github.com/NixOS/nixpkgs/pull/209107

**Comment by edmonds** [comment]
Done in #486
