### ISSUE TITLE
Protocol message contained an invalid tag (zero).

### ISSUE THREAD

**Issue by lipnitsk** [protobuf-c/protobuf-c#57]
_From [paceda...@gmail.com](https://code.google.com/u/117196726186269961029/) on January 30, 2011 11:35:52_

What steps will reproduce the problem? 1. Use protobuf-c example-client against another non-c server
2. We use java server, specifically protobuf-rpc-pro, but see problem in other servers tested 3. What is the expected output? What do you see instead? Sending a simple "name" test, throws exception immediately. It basically is confused about the TCP message length from what we can gather. What version of the product are you using? On what operating system? 0.14 and have tried svn checkout as well.  Mac OS X 10.5.8 Please provide any additional information below. com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).

_Original issue: http://code.google.com/p/protobuf-c/issues/detail?id=57_

**Comment by phoenixJu** [comment]
ok，how to solve it with this situation？？

**Comment by theanubhava** [comment]
I am facing the same problem in XXX.parseFrom() method. I have put my data in byte[] format and trying to read back, and then convert to the object.
But i am getting this weird error.
Can someone help with the solution here? please?
