### ISSUE TITLE
Does not configure (command_line_interface.h not found / /protobuf-c-config.h.in does not exist)

### ISSUE THREAD

**Issue by lipnitsk** [protobuf-c/protobuf-c#58]
_From [dan...@dseifert.de](https://code.google.com/u/107035189910127418108/) on March 12, 2011 04:41:05_

Same issue as in #45 but I don't see what the solution was, possibly because there is no documentation on requirements and installation instructions.

Does not matter whether I use SVN or the 0.15 tar.gz file, both ./configure and "mkdir build; cd build; cmake .." bring errors.

configure complains about google/protobuf/compiler/command_line_interface.h: No such file or directory

and cmake complains about "File {path}/protobuf-c-0.15/src/google/protobuf-c/protobuf-c-config.h.in does not exist.", presumably because configure did not run through?

BTW, /usr/include/google/protobuf does not have a "compiler" directory.

I am running on Ubuntu 10.10, svn r280 . Installed Ubuntu packages are libprotobuf-c0, libprotobuf-c0-dev, libprotobuf-dev, libprotobuf-lite6, libprotobuf6, protobuf-c-compiler, protobuf-compiler, python-protobuf

_Original issue: http://code.google.com/p/protobuf-c/issues/detail?id=58_

**Comment by Leser1990** [comment]
add  --disable-protoc   
when execut the ./configure
