### ISSUE TITLE
The libprotobuf-c.so.1.0.0 gets generated instead of a libprotobuf-c.so.1.4.0, why is that?

### ISSUE THREAD

**Issue by hpe-ykoehler** [protobuf-c/protobuf-c#693]
When I compile the module using the provided instructions, I am getting a libprotobuf-c.so.1.0.0 created, where this is v1.4.1 I am building.

```
 /bin/bash ./libtool   --mode=install /usr/bin/install -c   protobuf-c/libprotobuf-c.la '/usr/local/lib'
libtool: install: /usr/bin/install -c protobuf-c/.libs/libprotobuf-c.so.1.0.0 /usr/local/lib/libprotobuf-c.so.1.0.0
```

I would have expected the file to be libprotobuf-c.so.1.4.1

**Comment by edmonds** [comment]
The three numbers in `libprotobuf-c.so.X.X.X` are the libtool `current`, `revision`, and `age` values, see https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html. They're not the package version.

> **_Never_** try to set the interface numbers so that they correspond to the release number of your package. This is an abuse that only fosters misunderstanding of the purpose of library versions.

Technically I think we probably should have incremented revision and/or age back when the `protobuf_c_empty_string` symbol was introduced, which at least is recorded accurately in the symbol versions file, for platforms that use symbol versioning.

The protobuf-c library is mature and stable at this point, a build of the protobuf-c version 1.4.1 library (or the upcoming 1.5.0) should be backwards compatible to binaries that were originally linked against the protobuf-c version 1.0.0 library.

**Comment by hpe-ykoehler** [comment]
Yeah, I read/learn libtool versioning approach.  I understand the idea for servers where you may not want to relink everything for a library fix.  In my context, embedded world, such things make no sense to us as we re-build/re-link all the time.

I agree with you that this is not a real issue after having learn this.
