### ISSUE TITLE
cannot compile in V1.5.0

### ISSUE THREAD

**Issue by hhx20120607** [protobuf-c/protobuf-c#706]
sources: protobuf-c v1.5.0 && protobuf 23.3
commands: export protobuf_CFLAGS="-I${HOME}/usr/protobuf/include" && export protobuf_LIBS="-L${HOME}/usr/protobuf/lib" && ./configure && make -j8
compiler: gnu gcc 13.2
logs:
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for g++... g++
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... none needed
checking dependency style of g++... gcc3
checking whether ln -s works... yes
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for wchar.h... yes
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking whether _XOPEN_SOURCE should be defined... no
checking for gcc option to enable large file support... none needed
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /home/users/haohuaixu/usr/compiler/gcc-13.2/x86_64-unknown-linux-gnu/bin/ld
checking if the linker (/home/users/haohuaixu/usr/compiler/gcc-13.2/x86_64-unknown-linux-gnu/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /home/users/haohuaixu/usr/compiler/gcc-13.2/bin/nm -B
checking the name lister (/home/users/haohuaixu/usr/compiler/gcc-13.2/bin/nm -B) interface... BSD nm
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking for /home/users/haohuaixu/usr/compiler/gcc-13.2/x86_64-unknown-linux-gnu/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for ar... ar
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /home/users/haohuaixu/usr/compiler/gcc-13.2/bin/nm -B output from gcc object... ok
checking for dlfcn.h... yes
checking whether the compiler supports GNU C++... (cached) yes
checking whether g++ accepts -g... (cached) yes
checking for g++ option to enable C++11 features... (cached) none needed
checking dependency style of g++... (cached) gcc3
checking how to run the C++ preprocessor... g++ -E
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/home/users/haohuaixu/usr/compiler/gcc-13.2/x86_64-unknown-linux-gnu/bin/ld -m elf_x86_64) supports sha
red libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for ld used by g++... /home/users/haohuaixu/usr/compiler/gcc-13.2/x86_64-unknown-linux-gnu/bin/ld -m elf_x86_64
checking if the linker (/home/users/haohuaixu/usr/compiler/gcc-13.2/x86_64-unknown-linux-gnu/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/home/users/haohuaixu/usr/compiler/gcc-13.2/x86_64-unknown-linux-gnu/bin/ld -m elf_x86_64) supports sha
red libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/home/users/haohuaixu/usr/compiler/gcc-13.2/x86_64-unknown-linux-gnu/bin/ld -m elf_x86_64) supports sha
red libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether C compiler accepts "-Werror=incompatible-pointer-types"... yes
checking whether C compiler accepts "-Werror=int-conversion"... yes
checking whether C compiler accepts "-Wnull-dereference"... yes
checking for doxygen... doxygen
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking whether g++ supports C++17 features with -std=c++17... yes
checking for protobuf... yes
checking for google/protobuf/compiler/command_line_interface.h... yes
checking for protoc... /home/users/haohuaixu/usr/protobuf/bin/protoc
checking if LD -Wl,--version-script works... yes
checking whether self tests are run under valgrind... no
checking whether to build with code coverage support... no
checking whether byte ordering is bigendian... no
configure: creating ./config.status
config.status: creating Makefile
config.status: creating protobuf-c/libprotobuf-c.pc
config.status: creating Doxyfile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands

    protobuf-c 1.5.0

        CC:                     gcc
        CFLAGS:                 -g -O2
        CXX:                    g++ -std=c++17
        CXXFLAGS:               -g -O2
        LDFLAGS:                -L/home/users/haohuaixu/usr/protobuf/lib
        LIBS:                   

        prefix:                 /usr/local
        sysconfdir:             ${prefix}/etc
        libdir:                 ${exec_prefix}/lib
        includedir:             ${prefix}/include
        pkgconfigdir:           ${libdir}/pkgconfig

        bigendian:              no
        protobuf version:       libprotoc 23.3

errors: (a lot of undefined reference errors)
subprocess.cc:(.text._ZN4absl12lts_2023012512log_internal10LogMessagelsILi25EEERS2_RAT__Kc[_ZN4absl12lts_2023012512log_internal10LogMess
agelsILi25EEERS2_RAT__Kc]+0x38): undefined reference to `absl::lts_20230125::log_internal::LogMessage::CopyToEncodedBuffer(std::basic_st
ring_view<char, std::char_traits<char> >, absl::lts_20230125::log_internal::LogMessage::StringType)'
/home/users/haohuaixu/usr/compiler/gcc-13.2/lib/gcc/x86_64-unknown-linux-gnu/13.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: /home/u
sers/haohuaixu/usr/protobuf/lib/libprotoc.a(subprocess.cc.obj): in function `absl::lts_20230125::log_internal::LogMessage& absl::lts_202
30125::log_internal::LogMessage::operator<< <9>(char const (&) [9])':
subprocess.cc:(.text._ZN4absl12lts_2023012512log_internal10LogMessagelsILi9EEERS2_RAT__Kc[_ZN4absl12lts_2023012512log_internal10LogMessa
gelsILi9EEERS2_RAT__Kc]+0x38): undefined reference to `absl::lts_20230125::log_internal::LogMessage::CopyToEncodedBuffer(std::basic_stri
ng_view<char, std::char_traits<char> >, absl::lts_20230125::log_internal::LogMessage::StringType)'
/home/users/haohuaixu/usr/compiler/gcc-13.2/lib/gcc/x86_64-unknown-linux-gnu/13.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: /home/u
sers/haohuaixu/usr/protobuf/lib/libprotoc.a(subprocess.cc.obj): in function `absl::lts_20230125::log_internal::LogMessage& absl::lts_202
30125::log_internal::LogMessage::operator<< <10>(char const (&) [10])':
subprocess.cc:(.text._ZN4absl12lts_2023012512log_internal10LogMessagelsILi10EEERS2_RAT__Kc[_ZN4absl12lts_2023012512log_internal10LogMess
agelsILi10EEERS2_RAT__Kc]+0x38): undefined reference to `absl::lts_20230125::log_internal::LogMessage::CopyToEncodedBuffer(std::basic_st
ring_view<char, std::char_traits<char> >, absl::lts_20230125::log_internal::LogMessage::StringType)'
/home/users/haohuaixu/usr/compiler/gcc-13.2/lib/gcc/x86_64-unknown-linux-gnu/13.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: /home/u
sers/haohuaixu/usr/protobuf/lib/libprotoc.a(zip_writer.cc.obj): in function `google::protobuf::compiler::ZipWriter::Write(std::string co
nst&, std::string const&)':
zip_writer.cc:(.text+0x2e2): undefined reference to `google::protobuf::io::CodedOutputStream::~CodedOutputStream()'
/home/users/haohuaixu/usr/compiler/gcc-13.2/lib/gcc/x86_64-unknown-linux-gnu/13.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: zip_wri
ter.cc:(.text+0x301): undefined reference to `google::protobuf::io::CodedOutputStream::~CodedOutputStream()'
/home/users/haohuaixu/usr/compiler/gcc-13.2/lib/gcc/x86_64-unknown-linux-gnu/13.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: /home/u
sers/haohuaixu/usr/protobuf/lib/libprotoc.a(zip_writer.cc.obj): in function `google::protobuf::compiler::ZipWriter::WriteDirectory()':
zip_writer.cc:(.text+0x67f): undefined reference to `google::protobuf::io::CodedOutputStream::~CodedOutputStream()'
/home/users/haohuaixu/usr/compiler/gcc-13.2/lib/gcc/x86_64-unknown-linux-gnu/13.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: zip_wri
ter.cc:(.text+0x695): undefined reference to `google::protobuf::io::CodedOutputStream::~CodedOutputStream()'
/home/users/haohuaixu/usr/compiler/gcc-13.2/lib/gcc/x86_64-unknown-linux-gnu/13.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: /home/u
sers/haohuaixu/usr/protobuf/lib/libprotoc.a(zip_writer.cc.obj): in function `google::protobuf::io::CodedOutputStream::HadError()':
zip_writer.cc:(.text._ZN6google8protobuf2io17CodedOutputStream8HadErrorEv[_ZN6google8protobuf2io17CodedOutputStream8HadErrorEv]+0x20): u
ndefined reference to `google::protobuf::io::EpsCopyOutputStream::FlushAndResetBuffer(unsigned char*)'
/home/users/haohuaixu/usr/compiler/gcc-13.2/lib/gcc/x86_64-unknown-linux-gnu/13.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: zip_wri
ter.cc:(.text._ZN6google8protobuf2io17CodedOutputStream8HadErrorEv[_ZN6google8protobuf2io17CodedOutputStream8HadErrorEv]+0x78): undefine
d reference to `absl::lts_20230125::log_internal::LogMessageFatal::LogMessageFatal(char const*, int, std::basic_string_view<char, std::c
har_traits<char> >)'
/home/users/haohuaixu/usr/compiler/gcc-13.2/lib/gcc/x86_64-unknown-linux-gnu/13.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: zip_wri
ter.cc:(.text._ZN6google8protobuf2io17CodedOutputStream8HadErrorEv[_ZN6google8protobuf2io17CodedOutputStream8HadErrorEv]+0xab): undefine
d reference to `absl::lts_20230125::log_internal::LogMessageFatal::~LogMessageFatal()'
/home/users/haohuaixu/usr/compiler/gcc-13.2/lib/gcc/x86_64-unknown-linux-gnu/13.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: zip_wri
ter.cc:(.text._ZN6google8protobuf2io17CodedOutputStream8HadErrorEv[_ZN6google8protobuf2io17CodedOutputStream8HadErrorEv]+0xc9): undefine
d reference to `absl::lts_20230125::log_internal::LogMessageFatal::~LogMessageFatal()'
/home/users/haohuaixu/usr/compiler/gcc-13.2/lib/gcc/x86_64-unknown-linux-gnu/13.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: /home/u
sers/haohuaixu/usr/protobuf/lib/libprotoc.a(zip_writer.cc.obj): in function `google::protobuf::io::CodedOutputStream::ByteCount() const'
:
zip_writer.cc:(.text._ZNK6google8protobuf2io17CodedOutputStream9ByteCountEv[_ZNK6google8protobuf2io17CodedOutputStream9ByteCountEv]+0x1f
): undefined reference to `google::protobuf::io::EpsCopyOutputStream::ByteCount(unsigned char*) const'
collect2: error: ld returned 1 exit status

**Comment by hhx20120607** [comment]
anyone can help me?

**Comment by wdlcola** [comment]
大佬请问一下是怎么解决的呢
