### ISSUE TITLE
does newest version support optional in proto3?

### ISSUE THREAD

**Issue by JonSmith2017** [protobuf-c/protobuf-c#739]
I install proto-gen-c 1.5 through mingw and protoc 28.2 , but get error while generating c files , 
`protoc --c_out=. .\ui.proto 

ui.proto: is a proto3 file that contains optional fields, but code generator protoc-gen-c hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.
--c_out: `

can anyone tell me if verison 1.5 support it ? (I  searched  changelog buf not found info about it)

**Comment by d-baranowski** [comment]
so does it?

**Comment by ddomnik** [comment]
> so does it?

https://github.com/protobuf-c/protobuf-c/issues/476 dont think so
