### ISSUE TITLE
enums in .proto causes build error with g++

### ISSUE THREAD

**Issue by lipnitsk** [protobuf-c/protobuf-c#77]
_From [akit...@gmail.com](https://code.google.com/u/107200403002604120800/) on January 21, 2012 16:05:14_

What steps will reproduce the problem? 1. Write a .proto file including an enum field
2. Generate .h and .c files from the .proto file
3. Write a .cc file like "Message msg = MESSAGE__INIT;"
4. Compile source files written in step 2 and 3 with g++ What is the expected output? What do you see instead? I expect no compile errors but get:

`error: invalid conversion from 'int' to 'Message__Enum {aka _Message__Enum}' [-fpermissive]`

What version of the product are you using? On what operating system? protobuf-c-0.15 on Debian GNU/Linux Please provide any additional information below.

_Original issue: http://code.google.com/p/protobuf-c/issues/detail?id=77_

**Comment by desbma** [comment]
I am hit by this bug too (g++ 4.8.4, Protobuf-c 1.2.1)

To reproduce, create test.proto with the following content:

    syntax = "proto2";
    
    message Msg {
        required Enum result = 1;
        enum Enum {
            VAL1 = 0;
            VAL2 = 1;
        }
    }

Then generate and compile:

    $ protoc-c -I. --c_out=. test.proto
    $ g++ test.pb-c.c -c -o test.pb-c.o

Which gives:

    In file included from test.pb-c.c:9:0:
    test.pb-c.c: In function ‘void response__init(Msg*)’:
    test.pb-c.h:38:9: error: invalid conversion from ‘int’ to ‘Msg__Enum {aka _Msg__Enum}’ [-fpermissive]
         , 0 }
             ^
    test.pb-c.c:13:27: note: in expansion of macro ‘MSG__INIT’
       static Msg init_value = MSG__INIT;

**Comment by robert-alfaro** [comment]
I know this is a little late...but I am experiencing this using C generate output. Any idea what's up?
Below, `WifiAuthMode` is defined as: 
```
enum WifiAuthMode {
    AUTH_UNKNOWN = 0;
    WPA2_PSK = 3;                  /**< WPA2_PSK */
    WPA2_ENTERPRISE = 5;  /**< WPA2_ENTERPRISE (not implemented -- reserved) */
}
```

```
../main/proto/wifi/wifi.pb-c.h:198:45: error: invalid conversion from 'int' to 'WifiAuthMode {aka _WifiAuthMode}' [-fpermissive]
     , NULL, 0,0, 0,0, NULL, 0,{0,NULL}, 0,0 }
```
